#
# Makefile for the linux squashfs routines.
#

-include /tmp/sqvars.mk

obj-$(CONFIG_SQUASHFS_LZMA) += squashfs.o
squashfs-$(CONFIG_SQUASHFS_LZMA) += inode.o
squashfs-$(CONFIG_SQUASHFS_LZMA) += squashfs2_0.o
squashfs-$(CONFIG_SQUASHFS_LZMA) += LzmaDecode.o
squashfs-$(CONFIG_SQUASHFS_LZMA) += uncomp.o
#squashfs-$(CONFIG_SQUASHFS_LZMA) += LzmaDecode.o
#squashfs-$(CONFIG_SQUASHFS_LZMA) += LzmaDecode.o
#squashfs-$(CONFIG_SQUASHFS_LZMA) += LzmaDecode.o
#squashfs-$(CONFIG_SQUASHFS_LZMA) += LzmaDecode.o
