/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 30864 $
 * $Date: 2012-07-11 10:54:54 +0800 (Wed, 11 Jul 2012) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/maple/rtk_maple_table_struct.h>

#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_IACL_FIELDS[] = 
{
    {   /* name     MAPLE_IACL_FIELD_11tf */
        /* lsp */   560,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_10tf */
        /* lsp */   544,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_9tf */
        /* lsp */   528,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_8tf */
        /* lsp */   512,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_7tf */
        /* lsp */   496,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_6tf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_5tf */
        /* lsp */   464,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_4tf */
        /* lsp */   448,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_3tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_2tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_1tf */
        /* lsp */   400,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_FIELD_0tf */
        /* lsp */   384,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_SPMMASK_FIXtf */
        /* lsp */   374,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_SPNtf */
        /* lsp */   368,
        /* len */   6,
    },
    {   /* name     MAPLE_IACL_MGNT_VLANtf */
        /* lsp */   367,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_DMAC_HIT_SWtf */
        /* lsp */   366,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_NOT_FIRST_FRAGtf */
        /* lsp */   365,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_FRAME_TYPE_L4tf */
        /* lsp */   362,
        /* len */   3,
    },
    {   /* name     MAPLE_IACL_FRAME_TYPEtf */
        /* lsp */   360,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_OTAG_FMTtf */
        /* lsp */   359,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_ITAG_FMTtf */
        /* lsp */   358,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_OTAG_EXISTtf */
        /* lsp */   357,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_ITAG_EXISTtf */
        /* lsp */   356,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_FRAME_TYPE_L2tf */
        /* lsp */   354,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_TIDtf */
        /* lsp */   352,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_11tf */
        /* lsp */   336,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_10tf */
        /* lsp */   320,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_9tf */
        /* lsp */   304,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_8tf */
        /* lsp */   288,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_7tf */
        /* lsp */   272,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_6tf */
        /* lsp */   256,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_5tf */
        /* lsp */   240,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_4tf */
        /* lsp */   224,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_3tf */
        /* lsp */   208,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_2tf */
        /* lsp */   192,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_1tf */
        /* lsp */   176,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_FIELD_0tf */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_BMSK_SPMMASK_FIXtf */
        /* lsp */   150,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_BMSK_SPNtf */
        /* lsp */   144,
        /* len */   6,
    },
    {   /* name     MAPLE_IACL_BMSK_MGNT_VLANtf */
        /* lsp */   143,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_DMAC_HIT_SWtf */
        /* lsp */   142,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_NOT_FIRST_FRAGtf */
        /* lsp */   141,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_FRAME_TYPE_L4tf */
        /* lsp */   138,
        /* len */   3,
    },
    {   /* name     MAPLE_IACL_BMSK_FRAME_TYPEtf */
        /* lsp */   136,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_BMSK_OTAG_FMTtf */
        /* lsp */   135,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_ITAG_FMTtf */
        /* lsp */   134,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_OTAG_EXISTtf */
        /* lsp */   133,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_ITAG_EXISTtf */
        /* lsp */   132,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_BMSK_FRAME_TYPE_L2tf */
        /* lsp */   130,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_BMSK_TIDtf */
        /* lsp */   128,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_VALIDtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_NOTtf */
        /* lsp */   126,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_AND1tf */
        /* lsp */   125,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_AND2tf */
        /* lsp */   124,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_IVALIDtf */
        /* lsp */   123,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_AIF4tf */
        /* lsp */   96,
        /* len */   9,
    },
    {   /* name     MAPLE_IACL_AIF3tf */
        /* lsp */   80,
        /* len */   10,
    },
    {   /* name     MAPLE_IACL_AIF2tf */
        /* lsp */   64,
        /* len */   14,
    },
    {   /* name     MAPLE_IACL_AIF1tf */
        /* lsp */   48,
        /* len */   14,
    },
    {   /* name     MAPLE_IACL_AIF0tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     MAPLE_IACL_DROPtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     MAPLE_IACL_FWD_SELtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_OVID_SELtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_IVID_SELtf */
        /* lsp */   11,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_FLT_SELtf */
        /* lsp */   10,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_LOG_SELtf */
        /* lsp */   9,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_RMK_SELtf */
        /* lsp */   8,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_METER_SELtf */
        /* lsp */   7,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_TAGST_SELtf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_MIR_SELtf */
        /* lsp */   5,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_NORPRI_SELtf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_CPUPRI_SELtf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_OTPID_SELtf */
        /* lsp */   2,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_ITPID_SELtf */
        /* lsp */   1,
        /* len */   1,
    },
    {   /* name     MAPLE_IACL_SHAPER_SELtf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_IP_MC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_CAM_IP_MC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_GIPtf */
        /* lsp */   12,
        /* len */   32,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_IP_MC_SIP_FIELDS[] = 
{
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_FID_RVIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     MAPLE_L2_CAM_IP_MC_SIP_SIPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_MC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_CAM_MC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_MC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_MC_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_CAM_MC_VIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_CAM_MC_MACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     MAPLE_L2_CAM_MC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_UC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_CAM_UC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_STATICtf */
        /* lsp */   83,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_AGEtf */
        /* lsp */   81,
        /* len */   2,
    },
    {   /* name     MAPLE_L2_CAM_UC_SLPtf */
        /* lsp */   76,
        /* len */   5,
    },
    {   /* name     MAPLE_L2_CAM_UC_VIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_CAM_UC_SA_BLKtf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_DA_BLKtf */
        /* lsp */   62,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_SUSPENDtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_NEXT_HOPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_CAM_UC_MACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     MAPLE_L2_CAM_UC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_IP_MC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_IP_MC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_IP_MC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_IP_MC_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_IP_MC_GIPtf */
        /* lsp */   12,
        /* len */   32,
    },
    {   /* name     MAPLE_L2_IP_MC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_IP_MC_SIP_FIELDS[] = 
{
    {   /* name     MAPLE_L2_IP_MC_SIP_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_IP_MC_SIP_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_IP_MC_SIP_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_IP_MC_SIP_FID_RVIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_IP_MC_SIP_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     MAPLE_L2_IP_MC_SIP_SIPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_MC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_MC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_MC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_MC_MC_PMSK_IDXtf */
        /* lsp */   76,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_MC_VIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_MC_MACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     MAPLE_L2_MC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_NEXT_HOP_FIELDS[] = 
{
    {   /* name     MAPLE_L2_NEXT_HOP_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_STATICtf */
        /* lsp */   83,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_AGEtf */
        /* lsp */   81,
        /* len */   2,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_SLPtf */
        /* lsp */   76,
        /* len */   5,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_VLAN_TARGETtf */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_ROUTE_IDXtf */
        /* lsp */   64,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_SA_BLKtf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_DA_BLKtf */
        /* lsp */   62,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_SUSPENDtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_NEXT_HOPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_MACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_NEXT_HOP_LEGACY_FIELDS[] = 
{
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_DPAtf */
        /* lsp */   76,
        /* len */   5,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_NEXT_HOPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_GWMAC_IDXtf */
        /* lsp */   25,
        /* len */   9,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_DVIDtf */
        /* lsp */   13,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_NEXT_HOP_LEGACY_VID_SELtf */
        /* lsp */   12,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_UC_FIELDS[] = 
{
    {   /* name     MAPLE_L2_UC_IP_MCtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_IP6_MCtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_STATICtf */
        /* lsp */   83,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_AGEtf */
        /* lsp */   81,
        /* len */   2,
    },
    {   /* name     MAPLE_L2_UC_SLPtf */
        /* lsp */   76,
        /* len */   5,
    },
    {   /* name     MAPLE_L2_UC_VIDtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     MAPLE_L2_UC_SA_BLKtf */
        /* lsp */   63,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_DA_BLKtf */
        /* lsp */   62,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_SUSPENDtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_NEXT_HOPtf */
        /* lsp */   60,
        /* len */   1,
    },
    {   /* name     MAPLE_L2_UC_MACtf */
        /* lsp */   12,
        /* len */   48,
    },
    {   /* name     MAPLE_L2_UC_FID_RVIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_LOG_FIELDS[] = 
{
    {   /* name     MAPLE_LOG_CNTRtf */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_MC_PMSK_FIELDS[] = 
{
    {   /* name     MAPLE_MC_PMSK_PMSKtf */
        /* lsp */   0,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_MSTI_FIELDS[] = 
{
    {   /* name     MAPLE_MSTI_STATE_PORT28tf */
        /* lsp */   56,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT27tf */
        /* lsp */   54,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT26tf */
        /* lsp */   52,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT25tf */
        /* lsp */   50,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT24tf */
        /* lsp */   48,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT23tf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT22tf */
        /* lsp */   44,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT21tf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT20tf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT19tf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT18tf */
        /* lsp */   36,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT17tf */
        /* lsp */   34,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT16tf */
        /* lsp */   32,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT15tf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT14tf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT13tf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT12tf */
        /* lsp */   24,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT11tf */
        /* lsp */   22,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT10tf */
        /* lsp */   20,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT9tf */
        /* lsp */   18,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT8tf */
        /* lsp */   16,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT7tf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT6tf */
        /* lsp */   12,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT5tf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT4tf */
        /* lsp */   8,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT3tf */
        /* lsp */   6,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT2tf */
        /* lsp */   4,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT1tf */
        /* lsp */   2,
        /* len */   2,
    },
    {   /* name     MAPLE_MSTI_STATE_PORT0tf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_ROUTING_FIELDS[] = 
{
    {   /* name     MAPLE_ROUTING_GATEWAY_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_UNTAG_FIELDS[] = 
{
    {   /* name     MAPLE_UNTAG_PMSKtf */
        /* lsp */   0,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_VLAN_FIELDS[] = 
{
    {   /* name     MAPLE_VLAN_MBRtf */
        /* lsp */   32,
        /* len */   29,
    },
    {   /* name     MAPLE_VLAN_FID_MSTItf */
        /* lsp */   5,
        /* len */   6,
    },
    {   /* name     MAPLE_VLAN_L2_HASH_KEY_UCtf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_L2_HASH_KEY_MCtf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_VLAN_PROFILEtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_VLAN_EGR_CNVT_FIELDS[] = 
{
    {   /* name     MAPLE_VLAN_EGR_CNVT_VALID1tf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORGPRI1tf */
        /* lsp */   188,
        /* len */   3,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORG_VID1tf */
        /* lsp */   176,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORG_VID_RNG_CHK1tf */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORGPRI1tf */
        /* lsp */   156,
        /* len */   3,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORG_VID1tf */
        /* lsp */   144,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORG_VID_RNG_CHK1tf */
        /* lsp */   128,
        /* len */   16,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_PORT_ID1tf */
        /* lsp */   118,
        /* len */   5,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_PORT_ID1tf */
        /* lsp */   113,
        /* len */   5,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_VID_SHIFT1tf */
        /* lsp */   112,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_NEW_VID1tf */
        /* lsp */   100,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_PRI_ASSIGN1tf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_NEW_PRI1tf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_VALID0tf */
        /* lsp */   95,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORGPRI0tf */
        /* lsp */   92,
        /* len */   3,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORG_VID0tf */
        /* lsp */   80,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_ORG_VID_RNG_CHK0tf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORGPRI0tf */
        /* lsp */   60,
        /* len */   3,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORG_VID0tf */
        /* lsp */   48,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_ORG_VID_RNG_CHK0tf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_PORT_ID0tf */
        /* lsp */   22,
        /* len */   5,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_BMSK_PORT_ID0tf */
        /* lsp */   17,
        /* len */   5,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_VID_SHIFT0tf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_NEW_VID0tf */
        /* lsp */   4,
        /* len */   12,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_PRI_ASSIGN0tf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     MAPLE_VLAN_EGR_CNVT_NEW_PRI0tf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif

