/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 50053 $
 * $Date: 2014-08-11 17:47:46 +0800 (Mon, 11 Aug 2014) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/maple/rtk_maple_table_struct.h>
#include <hal/chipdef/maple/rtk_maple_tableField_list.h>

rtk_table_t rtk_maple_table_list[] =
{
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_IACL */
        /* access table type */     1,
        /* table size */            1536,
        /* total data registers */  18,
        /* total field numbers */   MAPLE_IACLFIELD_LIST_END,
        /* table fields */          RTL8380_IACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_CAM_IP_MC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_CAM_IP_MCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_CAM_IP_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_CAM_IP_MC_SIP */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_CAM_IP_MC_SIPFIELD_LIST_END,
        /* table fields */          RTL8380_L2_CAM_IP_MC_SIP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_CAM_MC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_CAM_MCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_CAM_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_CAM_UC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_CAM_UCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_CAM_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_IP_MC */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_IP_MCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_IP_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_IP_MC_SIP */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_IP_MC_SIPFIELD_LIST_END,
        /* table fields */          RTL8380_L2_IP_MC_SIP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_MC */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_MCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_NEXT_HOP */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_NEXT_HOPFIELD_LIST_END,
        /* table fields */          RTL8380_L2_NEXT_HOP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_NEXT_HOP_LEGACY */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_NEXT_HOP_LEGACYFIELD_LIST_END,
        /* table fields */          RTL8380_L2_NEXT_HOP_LEGACY_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_L2_UC */
        /* access table type */     0,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MAPLE_L2_UCFIELD_LIST_END,
        /* table fields */          RTL8380_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_LOG */
        /* access table type */     3,
        /* table size */            128,
        /* total data registers */  2,
        /* total field numbers */   MAPLE_LOGFIELD_LIST_END,
        /* table fields */          RTL8380_LOG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_MC_PMSK */
        /* access table type */     2,
        /* table size */            512,
        /* total data registers */  1,
        /* total field numbers */   MAPLE_MC_PMSKFIELD_LIST_END,
        /* table fields */          RTL8380_MC_PMSK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_MSTI */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  2,
        /* total field numbers */   MAPLE_MSTIFIELD_LIST_END,
        /* table fields */          RTL8380_MSTI_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_ROUTING */
        /* access table type */     2,
        /* table size */            512,
        /* total data registers */  2,
        /* total field numbers */   MAPLE_ROUTINGFIELD_LIST_END,
        /* table fields */          RTL8380_ROUTING_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_UNTAG */
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  1,
        /* total field numbers */   MAPLE_UNTAGFIELD_LIST_END,
        /* table fields */          RTL8380_UNTAG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_VLAN */
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   MAPLE_VLANFIELD_LIST_END,
        /* table fields */          RTL8380_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8380)
    {   /* table name               INT_MAPLE_RTL8380_VLAN_EGR_CNVT */
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  6,
        /* total field numbers */   MAPLE_VLAN_EGR_CNVTFIELD_LIST_END,
        /* table fields */          RTL8380_VLAN_EGR_CNVT_FIELDS
    },
#endif
};

#if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
rtk_tableName_t rtk_maple_tableName_list[] =
{
    {"IACL"},
    {"L2_CAM_IP_MC"},
    {"L2_CAM_IP_MC_SIP"},
    {"L2_CAM_MC"},
    {"L2_CAM_UC"},
    {"L2_IP_MC"},
    {"L2_IP_MC_SIP"},
    {"L2_MC"},
    {"L2_NEXT_HOP"},
    {"L2_NEXT_HOP_LEGACY"},
    {"L2_UC"},
    {"LOG"},
    {"MC_PMSK"},
    {"MSTI"},
    {"ROUTING"},
    {"UNTAG"},
    {"VLAN"},
    {"VLAN_EGR_CNVT"},
};
#endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */

