/*
 * Copyright (C) 2011 Realtek Semiconductor Corp.
 * All Rights Reserved.
 *
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * $Revision: 46645 $
 * $Date: 2014-02-26 19:43:48 +0800 (Wed, 26 Feb 2014) $
 *
 * Purpose : define supported command flags for 8389
 *
 * Feature : None
 *
 */

#ifndef __CMD_FLAG_RTL8389_H__
#define __CMD_FLAG_RTL8389_H__

/*
 * Include Files
 */


/*
 * Symbol Definition
 */
/* Bandwidth */

/* Flow Control */

/* LTU */

/* OAM */

/* CFM */

/* Trunk */
#define CMD_TRUNK_DUMP_TRUNK_GROUP_TRUNK_ID
#define CMD_TRUNK_GET_MODE
#define CMD_TRUNK_GET_DISTRIBUTE_ALGORITHM_TRUNK_GROUP_TRUNK_ID
#define CMD_TRUNK_GET_HASH_MAPPING_TRUNK_GROUP_TRUNK_ID
#define CMD_TRUNK_GET_MEMBER_PORT_TRUNK_GROUP_TRUNK_ID
#define CMD_TRUNK_SET_DISTRIBUTE_ALGORITHM_TRUNK_GROUP_TRUNK_ID_SRC_PORT_SRC_MAC_DST_MAC_SRC_IP_DST_IP_SRC_L4_PORT_DST_L4_PORT
//#define CMD_TRUNK_SET_HASH_MAPPING_TRUNK_GROUP_TRUNK_ID_HASH_VALUE_VALUE_PORT_PORT
#define CMD_TRUNK_SET_MEMBER_PORT_TRUNK_GROUP_TRUNK_ID_PORTS_NONE
#define CMD_TRUNK_SET_MODE_DUMB_NORMAL

/* Mirror */
#define CMD_MIRROR_CREATE_DESTROY_MIRRORING_PORT_PORT
#define CMD_MIRROR_DESTROY_ALL
#define CMD_MIRROR_GET_MIRRORING_PORT_PORT
#define CMD_MIRROR_SET_INGRESS_EGRESS_MIRRORING_PORT_PORT_MIRRORED_PORT_PORTS

/* EEE */
#define CMD_EEE_GET_PORT_PORTS_ALL_STATE
#define CMD_EEE_SET_PORT_PORTS_ALL_STATE_DISABLE_ENABLE

/* QoS */

/* MIB */

/* MPLS */

/* VLAN */
#define CMD_VLAN_CREATE_VLAN_TABLE_VID_VID
#define CMD_VLAN_DESTROY_VLAN_TABLE_VID_VID
#define CMD_VLAN_DESTROY_ALL_RESTORE_DEFAULT_VLAN
#define CMD_VLAN_SET_VLAN_TABLE_VID_VID_FILTER_ID_FID
#define CMD_VLAN_SET_VLAN_TABLE_VID_VID_MSTI_MSTI
#define CMD_VLAN_SET_VLAN_TABLE_VID_VID_MEMBER_PORTS_ALL_NONE
#define CMD_VLAN_SET_VLAN_TABLE_VID_VID_UNTAG_MEMBER_PORTS_ALL_NONE
#define CMD_VLAN_SET_ACCEPT_FRAME_TYPE_INNER_PORT_PORTS_ALL_ALL_TAG_ONLY_UNTAG_ONLY
#define CMD_VLAN_SET_STATE_ENABLE_DISABLE
#define CMD_VLAN_SET_INGRESS_FILTER_STATE_ENABLE_DISABLE
#define CMD_VLAN_SET_VLAN_LEAKY_MULTICAST_STATE_ENABLE_DISABLE
#define CMD_VLAN_SET_PVID_INNER_PORT_PORTS_ALL_PVID
#define CMD_VLAN_GET_VLAN_TABLE_VID_VID
#define CMD_VLAN_GET_ACCEPT_FRAME_TYPE_INNER_PORT_PORTS_ALL
#define CMD_VLAN_GET_STATE
#define CMD_VLAN_GET_INGRESS_FILTER_STATE
#define CMD_VLAN_GET_LEAKY_MULTICAST_STATE
#define CMD_VLAN_GET_PVID_INNER_PORT_PORTS_ALL
#define CMD_VLAN_DUMP_INGRESS_EGRESS_PORT_PORTS_ALL
#define CMD_VLAN_GET_TAG_MODE_PORT_PORTS_ALL


/* sFlow */

/* Storm Control */

/* ACL */

/* SECURITY */

/* Switch */

/* STP */

/* Port */
#define CMD_PORT_DUMP_CPU_PORT
#define CMD_PORT_DUMP_ISOLATION
#define CMD_PORT_DUMP_PORT_PORTS_ALL
#define CMD_PORT_DUMP_RLDP_PORT_PORTS_ALL
#define CMD_PORT_DUMP_ISOLATION_VLAN_BASED
#define CMD_PORT_GET_PHY_REG_PORT_PORTS_ALL
#define CMD_PORT_GET_PHY_REG_PORT_PORTS_ALL_PAGE_PAGE
#define CMD_PORT_GET_PHY_REG_PORT_PORTS_ALL_PAGE_PAGE_REGISTER_REGISTER
#define CMD_PORT_GET_PHY_REG_PORT_PORTS_ALL_PAGE_PAGE_REGISTER_REGISTER_NUMBER_NUMBER
#define CMD_PORT_GET_BACK_PRESSURE_PORT_PORTS_ALL_STATE
#define CMD_PORT_GET_AUTO_NEGO_PORT_PORTS_ALL_STATE
#define CMD_PORT_GET_AUTO_NEGO_PORT_PORTS_ALL_ABILITY
#define CMD_PORT_GET_ISOLATION_SRC_PORT_SRC_PORTS
#define CMD_PORT_GET_PHY_FORCE_PORT_PORTS_ALL
#define CMD_PORT_GET_RX_TX_PORT_PORTS_ALL_STATE
#define CMD_PORT_GET_PORT_PORTS_ALL_STATE
#define CMD_PORT_GET_COMBO_MODE_PORT_PORTS_ALL
#define CMD_PORT_SET_AUTO_NEGO_PORT_PORTS_ALL_ABILITY_10H_10F_100H_100F_1000F_FLOW_CONTROL_ASY_FLOW_CONTROL
#define CMD_PORT_SET_AUTO_NEGO_PORT_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_BACK_PRESSURE_PORT_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_COMBO_MODE_PORT_PORTS_ALL_COPPER_FORCE_FIBER_FORCE_AUTO_PREFERRED_COPPER_AUTO_PREFERRED_FIBER_AUTO_PREFERRED_FIBER_BY_GPIO
#define CMD_PORT_SET_PHY_FORCE_PORT_PORTS_ALL_ABILITY_10H_10F_100H_100F_1000F
#define CMD_PORT_SET_PHY_FORCE_PORT_PORTS_ALL_FLOW_CONTROL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_ISOLATION_SRC_PORT_SRC_PORTS_DST_PORT_DST_PORTS_ALL
#define CMD_PORT_SET_PHY_BCAST_REG_BCAST_ID_BROADCAST_ID
#define CMD_PORT_SET_PHY_REG_BROADCAST_PAGE_PAGE_REGISTER_REGISTER_DATA_DATA
#define CMD_PORT_SET_PHY_REG_PORT_PORTS_ALL_PAGE_PAGE_REGISTER_REGISTER_DATA_DATA
#define CMD_PORT_SET_PHY_EXT_REG_PORT_PORTS_ALL_MAIN_PAGE_MAINPAGE_EXT_PAGE_EXTPAGE_PARK_PAGE_PARKPAGE_REGISTER_REGISTER_DATA_DATA
#define CMD_PORT_SET_PHY_MMD_REG_PORT_PORTS_ALL_MMD_ADDR_MMD_ADDR_MMD_REG_MMD_REG_DATA_DATA
#define CMD_PORT_SET_RX_TX_PORT_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_PORT_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_GET_MASTER_SLAVE_PORT_PORTS_ALL
#define CMD_PORT_SET_MASTER_SLAVE_PORT_PORTS_ALL_AUTO_MASTER_SLAVE
#define CMD_PORT_SET_CROSS_OVER_PORT_PORTS_ALL_MODE_AUTO_MDI_MDIX
#define CMD_PORT_GET_CROSS_OVER_PORT_PORTS_ALL_MODE
#define CMD_PORT_GET_GREEN_PORT_PORTS_ALL_STATE
#define CMD_PORT_SET_GREEN_PORT_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_GET_PORT_PORTS_ALL_GIGA_LITE_DISABLE_ENABLE
#define CMD_PORT_SET_PORT_PORTS_ALL_GIGA_LITE_DISABLE_ENABLE
#define CMD_PORT_GET_LINK_DOWN_POWER_SAVING_PORT_ALL_STATE
#define CMD_PORT_SET_LINK_DOWN_POWER_SAVING_PORT_ALL_STATE_DISABLE_ENABLE

/* TIME */
#define CMD_TIME_GET_PTP_PORT_PORTS_ALL_STATE
#define CMD_TIME_SET_PTP_PORT_PORTS_ALL_STATE_ENABLE_DISABLE
#define CMD_TIME_GET_PTP_PORT_PORTS_ALL_TIME_STAMP_RX_MESSAGE_TYPE_DELAY_REQUEST_PEER_DELAY_REQUEST_PEER_DELAY_RESPONSE_SYNC_SEQUENCE_ID_SEQUENCE_ID
#define CMD_TIME_GET_PTP_PORT_PORTS_ALL_TIME_STAMP_TX_MESSAGE_TYPE_DELAY_REQUEST_PEER_DELAY_REQUEST_PEER_DELAY_RESPONSE_SYNC_SEQUENCE_ID_SEQUENCE_ID
#define CMD_TIME_GET_REFERENCE_TIME
#define CMD_TIME_SET_REFERENCE_TIME_SECOND_SECOND_NANOSECOND_NANOSECOND
#define CMD_TIME_SET_REFERENCE_TIME_INCREASE_DECREASE_SECOND_SECOND_NANOSECOND_NANOSECOND
#define CMD_TIME_GET_REFERENCE_TIME_STATE
#define CMD_TIME_SET_REFERENCE_TIME_STATE_ENABLE_DISABLE

/* TRAP */

/* L3 */

/* Diag */
#define CMD_DIAG_GET_CABLE_DOCTOR_PORT_PORTS_ALL
#define CMD_DIAG_SET_CABLE_DOCTOR_PORT_PORTS_ALL_START

/* LED */


/*
 * Data Declaration
 */


/*
 * Macro Declaration
 */


/*
 * Function Declaration
 */

/* Module Name : diag */


#endif /* __CMD_FLAG_RTL8389_H__ */

