/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef CPU_H
#define CPU_H

struct cpu_occupy
{
	char name[20];
	unsigned int user;
	unsigned int nice;
	unsigned int system;
	unsigned int idle;
	unsigned int iowait;
	unsigned int irq;
	unsigned int softirq;
};





/* function declarations */
void init_cpu(void);
Netsnmp_Node_Handler handle_cpuName;
Netsnmp_Node_Handler handle_cpuIdle;

#endif /* CPU_H */
