/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#if HAVE_STDLIB_H
#include <stdlib.h>
#endif
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "cpu.h"

char cidle[10]="89.00%";
char cname[10] = "armv7";

int get_cpuinfo()
{
	FILE	* in;
	char      line[1024];
	struct  cpu_occupy cpuinfo;
	unsigned int totaltime;
	double idle_percent;
	
	in = fopen("/proc/stat", "r");
    if (!in) {
        snmp_log(LOG_ERR, "snmpd: Cannot open /proc/stat\n");
        return -1;
    }
	fgets(line, sizeof(line), in);
	
	if (sscanf(line,"%s %d %d %d %d %d %d %d %*d %*d %*d\n",
                   &cpuinfo.name, &cpuinfo.user, &cpuinfo.nice, 
				   &cpuinfo.system, &cpuinfo.idle, &cpuinfo.iowait,
				   &cpuinfo.irq, &cpuinfo.softirq) != 8) {
            snmp_log(LOG_ERR, "Bad line in /proc/stat: %s", line);
            return -1;
    }
	
	totaltime = cpuinfo.user + cpuinfo.nice + cpuinfo.system + cpuinfo.idle + cpuinfo.iowait + cpuinfo.irq + cpuinfo.softirq;
	idle_percent = (double)cpuinfo.idle * 100 / totaltime;
	
	sprintf(cidle, "%0.2f", idle_percent);
	fclose(in);
	return 0;
}

/** Initializes the cpu module */
void
init_cpu(void)
{
    const oid cpuName_oid[] = { 1,3,6,1,2,1,12,1 };
    const oid cpuIdle_oid[] = { 1,3,6,1,2,1,12,2 };

  DEBUGMSGTL(("cpu", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuName", handle_cpuName,
                               cpuName_oid, OID_LENGTH(cpuName_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("cpuIdle", handle_cpuIdle,
                               cpuIdle_oid, OID_LENGTH(cpuIdle_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_cpuName(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */cname,
                                     /* XXX: the length of the data in bytes */sizeof(cname));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuName\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_cpuIdle(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
			get_cpuinfo();
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */cidle,
                                     /* XXX: the length of the data in bytes */sizeof(cidle));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_cpuIdle\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
