#
# Copyright (C) 2009 Realtek Semiconductor Corp. 
#
# Makefile for the RTL8389 specific parts of the kernel
#

EXTRA_CFLAGS += -I$(SDK_INCLUDE) -I$(SYS_INCLUDE)

obj-y	 	:= setup.o printf.o int.o mem.o

EXTRA_AFLAGS := $(CFLAGS)
