#!/bin/bash

# target fold
rtl819xs_usb_fold=rtl819xs_usb_linux_v2.6.0005.20090930
rtl8712_sdio_fold=rtl8712_sdio_linux_v2.6.0005.20090930

release_usb()
{
  rm -fr $rtl819xs_usb_fold.tar.gz
  
	mkdir $rtl819xs_usb_fold
	mkdir $rtl819xs_usb_fold/cmd
	mkdir $rtl819xs_usb_fold/crypto
	mkdir $rtl819xs_usb_fold/debug
	mkdir $rtl819xs_usb_fold/eeprom
	mkdir $rtl819xs_usb_fold/efuse
	mkdir $rtl819xs_usb_fold/hal
	mkdir $rtl819xs_usb_fold/hal/rtl8712
	mkdir $rtl819xs_usb_fold/include
	mkdir $rtl819xs_usb_fold/io
	mkdir $rtl819xs_usb_fold/ioctl
	mkdir $rtl819xs_usb_fold/mlme
	mkdir $rtl819xs_usb_fold/mp
	mkdir $rtl819xs_usb_fold/os_dep
	mkdir $rtl819xs_usb_fold/os_dep/linux
	mkdir $rtl819xs_usb_fold/os_intf
	mkdir $rtl819xs_usb_fold/os_intf/linux
	mkdir $rtl819xs_usb_fold/pwrctrl
	mkdir $rtl819xs_usb_fold/recv
	mkdir $rtl819xs_usb_fold/rf
	mkdir $rtl819xs_usb_fold/sta_mgt
	mkdir $rtl819xs_usb_fold/xmit

	cp Makefile_lx $rtl819xs_usb_fold/Makefile
	cp conf/config_rtl8712_usb_linux $rtl819xs_usb_fold/config
	cp script/wlan0dhcp $rtl819xs_usb_fold/.
	cp script/ifcfg-wlan0 $rtl819xs_usb_fold/.
	cp script/wpa1.conf $rtl819xs_usb_fold/.
	cp script/runwpa $rtl819xs_usb_fold/.
	
	cp cmd/rtl871x_cmd.c $rtl819xs_usb_fold/cmd/.
	cp cmd/rtl8712_cmd.c $rtl819xs_usb_fold/cmd/.	
	
	cp crypto/rtl871x_security.c $rtl819xs_usb_fold/crypto/.
		
	cp debug/rtl871x_debug.c $rtl819xs_usb_fold/debug/.		
	
	cp eeprom/rtl871x_eeprom.c $rtl819xs_usb_fold/eeprom/.
	
	cp efuse/rtl8712_efuse.c $rtl819xs_usb_fold/efuse/.
	
	cp hal/rtl8712/hal_init.c $rtl819xs_usb_fold/hal/rtl8712/.
	cp hal/rtl8712/usb_halinit.c $rtl819xs_usb_fold/hal/rtl8712/.
	cp hal/rtl8712/usb_ops.c $rtl819xs_usb_fold/hal/rtl8712/.
	cp hal/rtl8712/usb_ops_linux.c $rtl819xs_usb_fold/hal/rtl8712/.
	
	cp io/rtl871x_io.c $rtl819xs_usb_fold/io/.
	cp io/rtl8712_io.c $rtl819xs_usb_fold/io/.
	
	cp ioctl/rtl871x_ioctl_linux.c $rtl819xs_usb_fold/ioctl/.
	cp ioctl/rtl871x_ioctl_set.c $rtl819xs_usb_fold/ioctl/.
	cp ioctl/rtl871x_ioctl_query.c $rtl819xs_usb_fold/ioctl/.
	cp ioctl/rtl871x_ioctl_rtl.c $rtl819xs_usb_fold/ioctl/.
	
	cp mlme/rtl871x_mlme.c $rtl819xs_usb_fold/mlme/.
	cp mlme/ieee80211.c $rtl819xs_usb_fold/mlme/.
	
	cp mp/rtl871x_mp.c $rtl819xs_usb_fold/mp/.
	cp mp/rtl871x_mp_ioctl.c $rtl819xs_usb_fold/mp/.
	
	cp os_dep/linux/xmit_linux.c $rtl819xs_usb_fold/os_dep/linux/.
	cp os_dep/linux/recv_linux.c $rtl819xs_usb_fold/os_dep/linux/.
	cp os_dep/linux/mlme_linux.c $rtl819xs_usb_fold/os_dep/linux/.
	cp os_dep/linux/cmd_linux.c $rtl819xs_usb_fold/os_dep/linux/.
	cp os_dep/linux/io_linux.c $rtl819xs_usb_fold/os_dep/linux/.
	
	cp os_intf/osdep_service.c $rtl819xs_usb_fold/os_intf/.
	cp os_intf/linux/os_intfs.c $rtl819xs_usb_fold/os_intf/linux/.
	cp os_intf/linux/usb_intf.c $rtl819xs_usb_fold/os_intf/linux/.
		
	cp pwrctrl/rtl871x_pwrctrl.c $rtl819xs_usb_fold/pwrctrl/.
	
	cp recv/rtl871x_recv.c $rtl819xs_usb_fold/recv/.
	cp recv/rtl8712_recv.c $rtl819xs_usb_fold/recv/.
	
	cp rf/rtl871x_rf.c $rtl819xs_usb_fold/rf/.
	cp rf/rtl8712_rf.c $rtl819xs_usb_fold/rf/.
	
	cp sta_mgt/rtl871x_sta_mgt.c $rtl819xs_usb_fold/sta_mgt/.
		
	cp xmit/rtl871x_xmit.c $rtl819xs_usb_fold/xmit/.
	cp xmit/rtl8712_xmit.c $rtl819xs_usb_fold/xmit/.

	cp -fr include/ $rtl819xs_usb_fold/.
	
	cp -i autoconf_rtl8712_usb_linux.h $rtl819xs_usb_fold/include/autoconf.h	
	cp -i autoconf_rtl8712_usb_linux.h $rtl819xs_usb_fold/.

	rm -rf $rtl819xs_usb_fold/include/.svn
	rm -rf $rtl819xs_usb_fold/include/byteorder/.svn
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/.svn
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/sdio_reg/.svn
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/ioreg_def/.svn
	rm -rf $rtl819xs_usb_fold/include/CVS
	rm -rf $rtl819xs_usb_fold/include/byteorder/CVS
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/CVS
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/sdio_reg/CVS
	rm -rf $rtl819xs_usb_fold/include/rtl8712_spec/ioreg_def/CVS
	
	rm -rf $rtl819xs_usb_fold/.svn
	rm -rf $rtl819xs_usb_fold/cmd/.svn
	rm -rf $rtl819xs_usb_fold/crypto/.svn
	rm -rf $rtl819xs_usb_fold/debug/.svn
	rm -rf $rtl819xs_usb_fold/eeprom/.svn
	rm -rf $rtl819xs_usb_fold/efuse/.svn
	rm -rf $rtl819xs_usb_fold/hal/.svn
	rm -rf $rtl819xs_usb_fold/hal/rtl8712/.svn
	rm -rf $rtl819xs_usb_fold/include/.svn
	rm -rf $rtl819xs_usb_fold/io/.svn
	rm -rf $rtl819xs_usb_fold/ioctl/.svn
	rm -rf $rtl819xs_usb_fold/mlme/.svn
	rm -rf $rtl819xs_usb_fold/mp/.svn
	rm -rf $rtl819xs_usb_fold/os_dep/.svn
	rm -rf $rtl819xs_usb_fold/os_dep/linux/.svn
	rm -rf $rtl819xs_usb_fold/os_intf/.svn
	rm -rf $rtl819xs_usb_fold/os_intf/linux/.svn
	rm -rf $rtl819xs_usb_fold/pwrctrl/.svn
	rm -rf $rtl819xs_usb_fold/recv/.svn
	rm -rf $rtl819xs_usb_fold/rf/.svn
	rm -rf $rtl819xs_usb_fold/sta_mgt/.svn
	rm -rf $rtl819xs_usb_fold/xmit/.svn
	
			
	tar -zcvf $rtl819xs_usb_fold.tar.gz $rtl819xs_usb_fold/
	#tar -zcvf $rtl819xs_usb_fold.tar.gz $rtl819xs_usb_fold/  > /dev/null 2>&1
	#rm -fr $rtl819xs_usb_fold
	
}

release_sdio()
{
  rm -fr $rtl8712_sdio_fold.tar.gz
}



# Select NIC type
echo "Please select interface type(1/2):"
select intf in USB SDIO; 
do
	echo "You have selected $intf"
        break
done

# Make
case "$intf" in
        "USB")
        release_usb;;
        "SDIO")
        release_sdio;;        
        *)
        echo "Unknown interface type"
	;;
esac
