/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 8997 $
 * $Date: 2010-04-12 15:05:35 +0800 (Mon, 12 Apr 2010) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/ssw/rtk_ssw_table_struct.h>

#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_L2CAM_TABLE_FIELDS[] = 
{
    {   /* name     SSW_L2CAM_TABLE_FIDf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     SSW_L2CAM_TABLE_M_CVIDf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     SSW_L2CAM_TABLE_SIPf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     SSW_L2CAM_TABLE_MACf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     SSW_L2CAM_TABLE_DIPf */
        /* lsp */   36,
        /* len */   28,
    },
    {   /* name     SSW_L2CAM_TABLE_IP_MULTIf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     SSW_L2CAM_TABLE_IP_CVIDf */
        /* lsp */   23,
        /* len */   12,
    },
    {   /* name     SSW_L2CAM_TABLE_AGEf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     SSW_L2CAM_TABLE_STATICf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     SSW_L2CAM_TABLE_INDEXf */
        /* lsp */   14,
        /* len */   9,
    },
    {   /* name     SSW_L2CAM_TABLE_AUTHf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     SSW_L2CAM_TABLE_DABLOCKf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     SSW_L2CAM_TABLE_SABLOCKf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     SSW_L2CAM_TABLE_SPAf */
        /* lsp */   14,
        /* len */   5,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_L2_TABLE_FIELDS[] = 
{
    {   /* name     SSW_L2_TABLE_SIPf */
        /* lsp */   64,
        /* len */   20,
    },
    {   /* name     SSW_L2_TABLE_MACf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     SSW_L2_TABLE_DIPf */
        /* lsp */   36,
        /* len */   28,
    },
    {   /* name     SSW_L2_TABLE_IP_MULTIf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     SSW_L2_TABLE_IP_CVIDf */
        /* lsp */   23,
        /* len */   12,
    },
    {   /* name     SSW_L2_TABLE_AGEf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     SSW_L2_TABLE_STATICf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     SSW_L2_TABLE_INDEXf */
        /* lsp */   14,
        /* len */   9,
    },
    {   /* name     SSW_L2_TABLE_AUTHf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     SSW_L2_TABLE_DABLOCKf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     SSW_L2_TABLE_SABLOCKf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     SSW_L2_TABLE_SPAf */
        /* lsp */   14,
        /* len */   5,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_LOG_TABLE_FIELDS[] = 
{
    {   /* name     SSW_LOG_TABLE_PKTCNTf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     SSW_LOG_TABLE_BYTECNTf */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_MULTICAST_INDEX_TABLE_FIELDS[] = 
{
    {   /* name     SSW_MULTICAST_INDEX_TABLE_PORTMSKf */
        /* lsp */   3,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_PIE89_TABLE_FIELDS[] = 
{
    {   /* name     SSW_PIE89_TABLE_DMACf */
        /* lsp */   560,
        /* len */   48,
    },
    {   /* name     SSW_PIE89_TABLE_SMACf */
        /* lsp */   512,
        /* len */   48,
    },
    {   /* name     SSW_PIE89_TABLE_DIPf */
        /* lsp */   480,
        /* len */   32,
    },
    {   /* name     SSW_PIE89_TABLE_SIPf */
        /* lsp */   448,
        /* len */   32,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWLABELf */
        /* lsp */   428,
        /* len */   20,
    },
    {   /* name     SSW_PIE89_TABLE_PKTCVIDf */
        /* lsp */   416,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_RVIDf */
        /* lsp */   416,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_DSTPORTf */
        /* lsp */   400,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_SRCPORTf */
        /* lsp */   384,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_ETHTYPEf */
        /* lsp */   368,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_IPPROTOf */
        /* lsp */   360,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_TOSf */
        /* lsp */   352,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_PKTCPRIf */
        /* lsp */   349,
        /* len */   3,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_SLPf */
        /* lsp */   344,
        /* len */   5,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_FRAMETYPEf */
        /* lsp */   342,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_PKTTAGIFf */
        /* lsp */   341,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_IPV6MLDf */
        /* lsp */   340,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_IPV6f */
        /* lsp */   339,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_IPV4f */
        /* lsp */   338,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_PKTSTAGIFf */
        /* lsp */   335,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_PKTSPRIf */
        /* lsp */   332,
        /* len */   3,
    },
    {   /* name     SSW_PIE89_TABLE_FLOWTABLE_PKTSVIDf */
        /* lsp */   320,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_TCPFLAGf */
        /* lsp */   344,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_SLPf */
        /* lsp */   339,
        /* len */   5,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_FRAMETYPEf */
        /* lsp */   337,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_IPV6MLDf */
        /* lsp */   336,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_IPV6f */
        /* lsp */   335,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_IPV4f */
        /* lsp */   334,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_PATTERNMATCHf */
        /* lsp */   332,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_INACL_PKTSVIDf */
        /* lsp */   320,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_ACTGROUPf */
        /* lsp */   313,
        /* len */   3,
    },
    {   /* name     SSW_PIE89_TABLE_SRAM_17Bf */
        /* lsp */   296,
        /* len */   17,
    },
    {   /* name     SSW_PIE89_TABLE_SRAM_7Bf */
        /* lsp */   289,
        /* len */   7,
    },
    {   /* name     SSW_PIE89_TABLE_VALIDf */
        /* lsp */   288,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_DMACf */
        /* lsp */   240,
        /* len */   48,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_SMACf */
        /* lsp */   192,
        /* len */   48,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_DIPf */
        /* lsp */   160,
        /* len */   32,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_SIPf */
        /* lsp */   128,
        /* len */   32,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWLABELf */
        /* lsp */   108,
        /* len */   20,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PKTCVIDf */
        /* lsp */   96,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_RVIDf */
        /* lsp */   96,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_DSTPORTf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_SRCPORTf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_ETHTYPEf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_IPPROTOf */
        /* lsp */   40,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_TOSf */
        /* lsp */   32,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PKTCPRIf */
        /* lsp */   29,
        /* len */   3,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_SLPf */
        /* lsp */   24,
        /* len */   5,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_FRAMETYPEf */
        /* lsp */   22,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PKTTAGIFf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_IPV6MLDf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_IPV6f */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_IPV4f */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PKTSTAGIFf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PKTSPRIf */
        /* lsp */   12,
        /* len */   3,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_FLOWTABLE_PKTSVIDf */
        /* lsp */   0,
        /* len */   12,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_TCPFLAGf */
        /* lsp */   24,
        /* len */   8,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_SLPf */
        /* lsp */   19,
        /* len */   5,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_FRAMETYPEf */
        /* lsp */   17,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_IPV6MLDf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_IPV6f */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_IPV4f */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_PATTERNMATCHf */
        /* lsp */   12,
        /* len */   2,
    },
    {   /* name     SSW_PIE89_TABLE_CARE_INACL_PKTSVIDf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_SVLAN_TABLE_FIELDS[] = 
{
    {   /* name     SSW_SVLAN_TABLE_SMBRf */
        /* lsp */   3,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8389)
rtk_tableField_t RTL8389_VLAN_TABLE_FIELDS[] = 
{
    {   /* name     SSW_VLAN_TABLE_MEMBER_SETf */
        /* lsp */   67,
        /* len */   29,
    },
    {   /* name     SSW_VLAN_TABLE_UNTAG_SETf */
        /* lsp */   38,
        /* len */   29,
    },
    {   /* name     SSW_VLAN_TABLE_FIDf */
        /* lsp */   26,
        /* len */   12,
    },
    {   /* name     SSW_VLAN_TABLE_MSTIf */
        /* lsp */   22,
        /* len */   4,
    },
};
#endif

