/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 8997 $
 * $Date: 2010-04-12 15:05:35 +0800 (Mon, 12 Apr 2010) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/ssw/rtk_ssw_table_struct.h>
#include <hal/chipdef/ssw/rtk_ssw_tableField_list.h>

rtk_table_t rtk_ssw_table_list[] =
{
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_L2CAM_TABLE */
        /* access table type */     3,
        /* table size */            16448,
        /* total data registers */  3,
        /* total field numbers */   SSW_L2CAM_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_L2CAM_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_L2_TABLE */
        /* access table type */     3,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   SSW_L2_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_L2_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_LOG_TABLE */
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   SSW_LOG_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_LOG_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_MULTICAST_INDEX_TABLE */
        /* access table type */     4,
        /* table size */            512,
        /* total data registers */  1,
        /* total field numbers */   SSW_MULTICAST_INDEX_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_MULTICAST_INDEX_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_PIE89_TABLE */
        /* access table type */     0,
        /* table size */            512,
        /* total data registers */  19,
        /* total field numbers */   SSW_PIE89_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_PIE89_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_SVLAN_TABLE */
        /* access table type */     5,
        /* table size */            64,
        /* total data registers */  1,
        /* total field numbers */   SSW_SVLAN_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_SVLAN_TABLE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8389)
    {   /* table name               INT_SSW_RTL8389_VLAN_TABLE */
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  3,
        /* total field numbers */   SSW_VLAN_TABLEFIELD_LIST_END,
        /* table fields */          RTL8389_VLAN_TABLE_FIELDS
    },
#endif
};

