#!/bin/sh
#

if [ $# -lt 2 ]; then echo "Usage: $0 <offset> <data>";  exit 1 ; fi

echo 0x$1 $2 4 > /proc/net/rtl8852ae/wlan0/write_reg
echo 0x$1 4 > /proc/net/rtl8852ae/wlan0/read_reg
cat /proc/net/rtl8852ae/wlan0/read_reg

