#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_RTL8192CD)		+= rtl8192cd/
obj-$(CONFIG_CROSSBAND_REPEATER_SUPPORT_WIFI5_WIFI6) += crossband_repeater.o
