/*
 * Copyright (C) 2011 Realtek Semiconductor Corp.
 * All Rights Reserved.
 *
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * $Revision: 30032 $
 * $Date: 2012-06-18 19:54:51 +0800 (Mon, 18 Jun 2012) $
 *
 * Purpose : define supported command flags for 8389
 *
 * Feature : None
 *
 */

#ifndef __CMD_FLAG_RTL8389_H__
#define __CMD_FLAG_RTL8389_H__

/*
 * Include Files
 */


/*
 * Symbol Definition
 */
/* Bandwidth */

/* Flow Control */

/* LTU */

/* OAM */

/* CFM */

/* Trunk */

/* Mirror */

/* EEE */

/* QoS */

/* MIB */

/* MPLS */

/* VLAN */

/* sFlow */

/* Storm Control */

/* ACL */

/* SECURITY */

/* Switch */
#define CMD_SWITCH_DUMP_DELAY
#define CMD_SWITCH_GET_CHKSUM_ERR_ACTION_L2_L3_L4_PORTS_ALL
#define CMD_SWITCH_GET_CRC_RECAL_PORTS_ALL
#define CMD_SWITCH_GET_DELAY_INTRALINK0_RX_INTRALINK0_TX_INTRALINK1_RX_INTRALINK1_TX_STATE
#define CMD_SWITCH_GET_IPV4_ADDR
#define CMD_SWITCH_GET_IPV6_ADDR
#define CMD_SWITCH_GET_MAC_ADDR
//#define CMD_SWITCH_GET_MAX_PKT_LEN
#define CMD_SWITCH_GET_MAX_PKT_LEN_PORT_PORTS_ALL
#define CMD_SWITCH_GET_MGMT_VLAN_ID_INNER_OUTER
#define CMD_SWITCH_GET_PROBE_INFORMATION
#define CMD_SWITCH_GET_SDK_VERSION
#define CMD_SWITCH_GET_SNAP_MODE_PORTS_ALL
#define CMD_SWITCH_GET_WATCHDOG_MODE
#define CMD_SWITCH_GET_WATCHDOG_STATE
#define CMD_SWITCH_SET_CHKSUM_ERR_ACTION_L2_L3_L4_PORTS_ALL_DROP_FORWARD
#define CMD_SWITCH_SET_CRC_RECAL_PORTS_ALL_STATE_DISABLE_ENABLE
#define CMD_SWITCH_SET_DELAY_INTRALINK0_RX_INTRALINK0_TX_INTRALINK1_RX_INTRALINK1_TX_STATE_DISABLE_ENABLE
#define CMD_SWITCH_SET_IPV4_ADDR_ADDR
#define CMD_SWITCH_SET_IPV6_ADDR_ADDR
#define CMD_SWITCH_SET_MAC_ADDR_ADDR
//#define CMD_SWITCH_SET_MAX_PKT_LEN_LEN
#define CMD_SWITCH_SET_MAX_PKT_LEN_PORT_PORTS_ALL_LEN
#define CMD_SWITCH_SET_MGMT_VLAN_ID_INNER_OUTER_VID
#define CMD_SWITCH_SET_SNAP_MODE_PORTS_ALL_SNAP03000000_SNAP03XXXXXX
#define CMD_SWITCH_SET_WATCHDOG_MODE_ISR_NORMAL
#define CMD_SWITCH_SET_WATCHDOG_STATE_DISABLE_ENABLE
#define CMD_SWITCH_GET_PKT2CPU_FORMAT
#define CMD_SWITCH_SET_PKT2CPU_FORMAT_MODIFIED_ORIGINAL

/* STP */

/* Port */
#define CMD_PORT_DUMP_CPU_PORT
#define CMD_PORT_DUMP_ISOLATION_PORT_ALL
#define CMD_PORT_DUMP_PORT_ALL
#define CMD_PORT_DUMP_RLDP_PORT_ALL
#define CMD_PORT_DUMP_UDLD_PORT_ALL
#define CMD_PORT_GET_AUTO_NEGO_PORT_ALL_ABILITY
#define CMD_PORT_GET_AUTO_NEGO_PORT_ALL_STATE
#define CMD_PORT_GET_BACK_PRESSURE_PORT_ALL_STATE
#define CMD_PORT_GET_COMBO_MODE_PORT_ALL
#define CMD_PORT_GET_COMBO_FIBER_MODE_PORT_ALL
#define CMD_PORT_GET_GREEN_PORT_ALL_STATE
#define CMD_PORT_GET_ISOLATION_SRC_PORT
#define CMD_PORT_GET_FORCE_PORT_ALL
#define CMD_PORT_GET_LINK_DOWN_POWER_SAVING_PORT_ALL_STATE
//#define CMD_PORT_GET_MAC_LOOPBACK_LOCAL_REMOTE_PORT_ALL_STATE
#define CMD_PORT_GET_PHY_REG_PORT_ALL_PAGE_REGISTER_NUMBER
#define CMD_PORT_GET_PHY_REG_PORT_ALL_PAGE
#define CMD_PORT_GET_PHY_REG_PORT_ALL
#define CMD_PORT_GET_PORT_ALL_STATE
#define CMD_PORT_SET_AUTO_NEGO_PORT_ALL_ABILITY_10H_10F_100H_100F_1000F_FLOW_CONTROL_ASY_FLOW_CONTROL
#define CMD_PORT_SET_AUTO_NEGO_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_BACK_PRESSURE_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_COMBO_MODE_PORT_ALL_COPPER_FORCE_FIBER_FORCE_AUTO_PREFERRED_COPPER_AUTO_PREFERRED_FIBER_AUTO_PREFERRED_FIBER_BY_GPIO
#define CMD_PORT_SET_COMBO_FIBER_MODE_PORT_ALL_FIBER_1000_FIBER_100_FIBER_AUTO
#define CMD_PORT_SET_FORCE_PORT_ALL_ABILITY_10H_10F_100H_100F_1000F_FLOW_CONTROL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_GREEN_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_ISOLATION_SRC_PORT_PORT_ALL
#define CMD_PORT_SET_LINK_DOWN_POWER_SAVING_PORT_ALL_STATE_DISABLE_ENABLE
//#define CMD_PORT_SET_MAC_LOOPBACK_LOCAL_REMOTE_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_PHY_REG_PORT_ALL_PAGE_REGISTER_DATA
#define CMD_PORT_SET_RX_TX_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_RLDP_AUTO_BLOCK_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_RLDP_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_RLDP_HELLO_TIME_NORMAL_LOOP_AGING_TIME_SELF_LOOP_AGING_TIME_PORT_ALL_1S_2S_4S_8S
#define CMD_PORT_SET_UDLD_AUTO_DISABLE_PORT_LED_INDICATION_LINKUP_AUTO_TRIG_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_UDLD_ECHO_GENERATE_INTERVAL_2S_4S_8S_16S
#define CMD_PORT_SET_UDLD_ECHO_REQUEST_RETRY_TIMES_1_2_4_8
#define CMD_PORT_SET_UDLD_ECHO_ACTION_FORWARD_SELFLOOP
#define CMD_PORT_SET_UDLD_LINK_STATUS_PORT_ALL_DISABLE_NORMAL
#define CMD_PORT_SET_UDLD_PORT_ALL_STATE_DISABLE_ENABLE
#define CMD_PORT_SET_UDLD_PORT_ALL_TRIGGER
//#define CMD_PORT_SET_RTCT_PORT_ALL_START
//#define CMD_PORT_GET_RTCT_PORT_ALL
#define CMD_PORT_SET_CROSS_OVER_PORT_ALL_MODE_AUTO_MDI_MDIX
#define CMD_PORT_GET_CROSS_OVER_PORT_ALL_MODE

/* TIME */

/* TRAP */

/* L3 */

/* Diag */

/* LED */


/*
 * Data Declaration
 */


/*
 * Macro Declaration
 */


/*
 * Function Declaration
 */

/* Module Name : diag */


#endif /* __CMD_FLAG_RTL8389_H__ */

