#ifndef __MW5_CONFIG_8192CD_H__
#define __MW5_CONFIG_8192CD_H__
#define CONFIG_RTL8192CD 1
#define CONFIG_WIRELESS_LAN_MODULE 1
#define CONFIG_WIFI_HCI 1
#define CONFIG_PCI_HCI 1
#define CONFIG_WLAN_HAL 1
#define CONFIG_WLAN_HAL_88XX 1
#define CONFIG_WLAN_HAL_8197F 1
#ifndef CONFIG_MW5_2G_ONLY
#define CONFIG_WLAN_HAL_8822BE 1
#define CONFIG_NET_PCI 1
#endif
#define CONFIG_RTL_ODM_WLAN_DRIVER 1
#define CONFIG_WLAN_MACHAL_API 1
#define CONFIG_WLAN_MACHAL_API_V0 1
#define CONFIG_RTL_VAP_SUPPORT 1
#define CONFIG_RTL_CLIENT_MODE_SUPPORT 1
#define CONFIG_RTL_REPEATER_MODE_SUPPORT 1
#define CONFIG_RTL_80211D_SUPPORT 1
#define CONFIG_RTL_11W_SUPPORT 1
#define CONFIG_TXPWR_LMT 1
#define CONFIG_RTL_8197F 1
#define CONFIG_RTL_8197F_VG 1
#define CONFIG_RTL_DISABLE_WLAN_MIPS16 1
#define CONFIG_BAND_2G_ON_WLAN0 1
#ifndef CONFIG_MW5_2G_ONLY
#define CONFIG_USE_PCIE_SLOT_1 1
#endif
#define CONFIG_SLOT_0_RFE_TYPE_5 1
#ifndef CONFIG_MW5_2G_ONLY
#define CONFIG_SLOT_1_8822BE 1
#endif
#define CONFIG_OPENWRT_SDK 1
#define _LITTLE_ENDIAN_ 1
#define NOT_RTK_BSP 1
#define CONFIG_MW5_LEGACY_WEXT 1
#define CONFIG_MW5_NO_LED 1
#endif
