/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 8997 $
 * $Date: 2010-04-12 15:05:35 +0800 (Mon, 12 Apr 2010) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/esw/rtk_esw_table_struct.h>

#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_ACL_COUNTER_FIELDS[] = 
{
    {   /* name     ESW_ACL_COUNTER_ACL_COUNTER_64_0f */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     ESW_ACL_COUNTER_ACL_COUNTER_64_1f */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_ACTTBL_FIELDS[] = 
{
    {   /* name     ESW_ACTTBL_HITINDf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_STATISTICSf */
        /* lsp */   189,
        /* len */   2,
    },
    {   /* name     ESW_ACTTBL_CP2CPUf */
        /* lsp */   188,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_DROPf */
        /* lsp */   186,
        /* len */   2,
    },
    {   /* name     ESW_ACTTBL_OUTTAGOPf */
        /* lsp */   185,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_REDIRf */
        /* lsp */   184,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_INTAGOPf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_PRIf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_DSCPf */
        /* lsp */   181,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_POLICE_OUTRMKf */
        /* lsp */   180,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_MIRRORf */
        /* lsp */   179,
        /* len */   1,
    },
    {   /* name     ESW_ACTTBL_AIF1f */
        /* lsp */   142,
        /* len */   18,
    },
    {   /* name     ESW_ACTTBL_AIF2f */
        /* lsp */   110,
        /* len */   18,
    },
    {   /* name     ESW_ACTTBL_AIF3f */
        /* lsp */   79,
        /* len */   17,
    },
    {   /* name     ESW_ACTTBL_AIF4f */
        /* lsp */   53,
        /* len */   11,
    },
    {   /* name     ESW_ACTTBL_AIF5f */
        /* lsp */   23,
        /* len */   9,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_CAM_ISFTIDX_FIELDS[] = 
{
    {   /* name     ESW_CAM_ISFTIDX_AED_59_28f */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     ESW_CAM_ISFTIDX_AED_27_0f */
        /* lsp */   36,
        /* len */   28,
    },
    {   /* name     ESW_CAM_ISFTIDX_AETf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISFTIDX_ISFTIDXf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISFTIDX_VALIDf */
        /* lsp */   33,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISFTIDX_FTIDXf */
        /* lsp */   22,
        /* len */   10,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_CAM_ISNOTFTIDX_FIELDS[] = 
{
    {   /* name     ESW_CAM_ISNOTFTIDX_AED_59_28f */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_AED_27_0f */
        /* lsp */   36,
        /* len */   28,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_AETf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_ISFTIDXf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_VALIDf */
        /* lsp */   33,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_PORTNUMf */
        /* lsp */   27,
        /* len */   5,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_SBLKf */
        /* lsp */   26,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_DOT1XMACAUTHf */
        /* lsp */   25,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_ISSTATICf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_AGINGf */
        /* lsp */   21,
        /* len */   3,
    },
    {   /* name     ESW_CAM_ISNOTFTIDX_SUSPENDf */
        /* lsp */   20,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_CBCCR_FIELDS[] = 
{
    {   /* name     ESW_CBCCR_CLR_ACTTBLf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_CBCCR_CLR_PIEf */
        /* lsp */   23,
        /* len */   1,
    },
    {   /* name     ESW_CBCCR_ENTRY_STARTf */
        /* lsp */   12,
        /* len */   11,
    },
    {   /* name     ESW_CBCCR_ENTRY_ENDf */
        /* lsp */   1,
        /* len */   11,
    },
    {   /* name     ESW_CBCCR_STOPALEf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_ENTRY_HIT_INDI_STA_FIELDS[] = 
{
    {   /* name     ESW_ENTRY_HIT_INDI_STA_ELKNHIT_31_0f */
        /* lsp */   96,
        /* len */   32,
    },
    {   /* name     ESW_ENTRY_HIT_INDI_STA_ELKNHIT_63_32f */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     ESW_ENTRY_HIT_INDI_STA_ELKNHIT_95_64f */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     ESW_ENTRY_HIT_INDI_STA_ELKNHIT_127_96f */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_FORWARDING_FIELDS[] = 
{
    {   /* name     ESW_FORWARDING_PMf */
        /* lsp */   32,
        /* len */   29,
    },
    {   /* name     ESW_FORWARDING_CRSVLANf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     ESW_FORWARDING_AGINGf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_L2_ISFTIDX_FIELDS[] = 
{
    {   /* name     ESW_L2_ISFTIDX_AED_47_16f */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     ESW_L2_ISFTIDX_AED_15_0f */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     ESW_L2_ISFTIDX_AETf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISFTIDX_ISFTIDXf */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISFTIDX_VALIDf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISFTIDX_FTIDXf */
        /* lsp */   3,
        /* len */   10,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_L2_ISNOTFTIDX_FIELDS[] = 
{
    {   /* name     ESW_L2_ISNOTFTIDX_AED_47_16f */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_AED_15_0f */
        /* lsp */   16,
        /* len */   16,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_AETf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_ISFTIDXf */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_VALIDf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_PORTNUMf */
        /* lsp */   8,
        /* len */   5,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_SBLKf */
        /* lsp */   7,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_DOT1XMACAUTHf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_ISSTATICf */
        /* lsp */   5,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_NHf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_AGINGf */
        /* lsp */   1,
        /* len */   3,
    },
    {   /* name     ESW_L2_ISNOTFTIDX_SUSPENDf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_MOVE_PIE_FIELDS[] = 
{
    {   /* name     ESW_MOVE_PIE_ENTRY_LENGTHf */
        /* lsp */   36,
        /* len */   11,
    },
    {   /* name     ESW_MOVE_PIE_ACTIONf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     ESW_MOVE_PIE_MOVE_RULEf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     ESW_MOVE_PIE_MOVE_ACLACTTBLf */
        /* lsp */   33,
        /* len */   1,
    },
    {   /* name     ESW_MOVE_PIE_STOPALEf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     ESW_MOVE_PIE_DIRECTIONf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     ESW_MOVE_PIE_MOVE_TOf */
        /* lsp */   11,
        /* len */   11,
    },
    {   /* name     ESW_MOVE_PIE_MOVE_FROMf */
        /* lsp */   0,
        /* len */   11,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_PIE_FIELDS[] = 
{
    {   /* name     ESW_PIE_DATA_31_0f */
        /* lsp */   288,
        /* len */   32,
    },
    {   /* name     ESW_PIE_DATA_63_32f */
        /* lsp */   256,
        /* len */   32,
    },
    {   /* name     ESW_PIE_DATA_95_64f */
        /* lsp */   224,
        /* len */   32,
    },
    {   /* name     ESW_PIE_DATA_127_96f */
        /* lsp */   192,
        /* len */   32,
    },
    {   /* name     ESW_PIE_VALIDf */
        /* lsp */   176,
        /* len */   1,
    },
    {   /* name     ESW_PIE_DATA_143_128f */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     ESW_PIE_CAREBIT_31_0f */
        /* lsp */   128,
        /* len */   32,
    },
    {   /* name     ESW_PIE_CAREBIT_63_32f */
        /* lsp */   96,
        /* len */   32,
    },
    {   /* name     ESW_PIE_CAREBIT_95_64f */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     ESW_PIE_CAREBIT_127_96f */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     ESW_PIE_CAREBIT_143_128f */
        /* lsp */   0,
        /* len */   16,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_POLICER_FIELDS[] = 
{
    {   /* name     ESW_POLICER_PBSf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_CBSf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_TPf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_TCf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_PIRf */
        /* lsp */   48,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_CIRf */
        /* lsp */   32,
        /* len */   16,
    },
    {   /* name     ESW_POLICER_YEL_DPf */
        /* lsp */   4,
        /* len */   2,
    },
    {   /* name     ESW_POLICER_RED_DPf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     ESW_POLICER_COLORAWAREf */
        /* lsp */   2,
        /* len */   1,
    },
    {   /* name     ESW_POLICER_TYPEf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_SPT_FIELDS[] = 
{
    {   /* name     ESW_SPT_PORT15_SPT_STATEf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT14_SPT_STATEf */
        /* lsp */   60,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT13_SPT_STATEf */
        /* lsp */   58,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT12_SPT_STATEf */
        /* lsp */   56,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT11_SPT_STATEf */
        /* lsp */   54,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT10_SPT_STATEf */
        /* lsp */   52,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT9_SPT_STATEf */
        /* lsp */   50,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT8_SPT_STATEf */
        /* lsp */   48,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT7_SPT_STATEf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT6_SPT_STATEf */
        /* lsp */   44,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT5_SPT_STATEf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT4_SPT_STATEf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT3_SPT_STATEf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT2_SPT_STATEf */
        /* lsp */   36,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT1_SPT_STATEf */
        /* lsp */   34,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT0_SPT_STATEf */
        /* lsp */   32,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT28_SPT_STATEf */
        /* lsp */   24,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT27_SPT_STATEf */
        /* lsp */   22,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT26_SPT_STATEf */
        /* lsp */   20,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT25_SPT_STATEf */
        /* lsp */   18,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT24_SPT_STATEf */
        /* lsp */   16,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT23_SPT_STATEf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT22_SPT_STATEf */
        /* lsp */   12,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT21_SPT_STATEf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT20_SPT_STATEf */
        /* lsp */   8,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT19_SPT_STATEf */
        /* lsp */   6,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT18_SPT_STATEf */
        /* lsp */   4,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT17_SPT_STATEf */
        /* lsp */   2,
        /* len */   2,
    },
    {   /* name     ESW_SPT_PORT16_SPT_STATEf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_VLAN_FIELDS[] = 
{
    {   /* name     ESW_VLAN_FIDf */
        /* lsp */   65,
        /* len */   7,
    },
    {   /* name     ESW_VLAN_VLAN_BASE_FWDf */
        /* lsp */   64,
        /* len */   1,
    },
    {   /* name     ESW_VLAN_UTAGf */
        /* lsp */   32,
        /* len */   29,
    },
    {   /* name     ESW_VLAN_MBRf */
        /* lsp */   0,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR0_FIELDS[] = 
{
    {   /* name     ESW_TSSCR0_BC_RATEf */
        /* lsp */   0,
        /* len */   20,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR1_FIELDS[] = 
{
    {   /* name     ESW_TSSCR1_BC_EXCSTf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR1_BC_COUNTERf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR2_FIELDS[] = 
{
    {   /* name     ESW_TSSCR2_BC_ENABLEf */
        /* lsp */   25,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR2_BC_BUNITf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR2_BC_BURSTf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR3_FIELDS[] = 
{
    {   /* name     ESW_TSSCR3_MC_RATEf */
        /* lsp */   0,
        /* len */   20,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR4_FIELDS[] = 
{
    {   /* name     ESW_TSSCR4_MC_EXCSTf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR4_MC_COUNTERf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR5_FIELDS[] = 
{
    {   /* name     ESW_TSSCR5_MC_TYPEf */
        /* lsp */   26,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR5_MC_ENABLEf */
        /* lsp */   25,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR5_MC_BUNITf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR5_MC_BURSTf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR6_FIELDS[] = 
{
    {   /* name     ESW_TSSCR6_UNUA_RATEf */
        /* lsp */   0,
        /* len */   20,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR7_FIELDS[] = 
{
    {   /* name     ESW_TSSCR7_UNUA_EXCSTf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR7_UNUA_COUNTERf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8328)
rtk_tableField_t RTL8328_TSSCR8_FIELDS[] = 
{
    {   /* name     ESW_TSSCR8_UNUA_ENABLEf */
        /* lsp */   25,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR8_UNUA_BUNITf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     ESW_TSSCR8_UNUA_BURSTf */
        /* lsp */   0,
        /* len */   24,
    },
};
#endif

