/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 8997 $
 * $Date: 2010-04-12 15:05:35 +0800 (Mon, 12 Apr 2010) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/esw/rtk_esw_table_struct.h>
#include <hal/chipdef/esw/rtk_esw_tableField_list.h>

rtk_table_t rtk_esw_table_list[] =
{
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_ACL_COUNTER */
        /* access table type */     6,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   ESW_ACL_COUNTERFIELD_LIST_END,
        /* table fields */          RTL8328_ACL_COUNTER_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_ACTTBL */
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  6,
        /* total field numbers */   ESW_ACTTBLFIELD_LIST_END,
        /* table fields */          RTL8328_ACTTBL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_CAM_ISFTIDX */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   ESW_CAM_ISFTIDXFIELD_LIST_END,
        /* table fields */          RTL8328_CAM_ISFTIDX_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_CAM_ISNOTFTIDX */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   ESW_CAM_ISNOTFTIDXFIELD_LIST_END,
        /* table fields */          RTL8328_CAM_ISNOTFTIDX_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_CBCCR */
        /* access table type */     9,
        /* table size */            1,
        /* total data registers */  1,
        /* total field numbers */   ESW_CBCCRFIELD_LIST_END,
        /* table fields */          RTL8328_CBCCR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_ENTRY_HIT_INDI_STA */
        /* access table type */     5,
        /* table size */            16,
        /* total data registers */  4,
        /* total field numbers */   ESW_ENTRY_HIT_INDI_STAFIELD_LIST_END,
        /* table fields */          RTL8328_ENTRY_HIT_INDI_STA_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_FORWARDING */
        /* access table type */     3,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   ESW_FORWARDINGFIELD_LIST_END,
        /* table fields */          RTL8328_FORWARDING_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_L2_ISFTIDX */
        /* access table type */     1,
        /* table size */            16384,
        /* total data registers */  2,
        /* total field numbers */   ESW_L2_ISFTIDXFIELD_LIST_END,
        /* table fields */          RTL8328_L2_ISFTIDX_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_L2_ISNOTFTIDX */
        /* access table type */     1,
        /* table size */            16384,
        /* total data registers */  2,
        /* total field numbers */   ESW_L2_ISNOTFTIDXFIELD_LIST_END,
        /* table fields */          RTL8328_L2_ISNOTFTIDX_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_MOVE_PIE */
        /* access table type */     10,
        /* table size */            1,
        /* total data registers */  2,
        /* total field numbers */   ESW_MOVE_PIEFIELD_LIST_END,
        /* table fields */          RTL8328_MOVE_PIE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_PIE */
        /* access table type */     8,
        /* table size */            2048,
        /* total data registers */  10,
        /* total field numbers */   ESW_PIEFIELD_LIST_END,
        /* table fields */          RTL8328_PIE_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_POLICER */
        /* access table type */     7,
        /* table size */            256,
        /* total data registers */  4,
        /* total field numbers */   ESW_POLICERFIELD_LIST_END,
        /* table fields */          RTL8328_POLICER_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_SPT */
        /* access table type */     11,
        /* table size */            128,
        /* total data registers */  2,
        /* total field numbers */   ESW_SPTFIELD_LIST_END,
        /* table fields */          RTL8328_SPT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_VLAN */
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  3,
        /* total field numbers */   ESW_VLANFIELD_LIST_END,
        /* table fields */          RTL8328_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR0 */
        /* access table type */     4,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR0FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR1 */
        /* access table type */     0,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR1FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR2 */
        /* access table type */     8,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR2FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR3 */
        /* access table type */     5,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR3FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR3_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR4 */
        /* access table type */     1,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR4FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR4_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR5 */
        /* access table type */     9,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR5FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR5_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR6 */
        /* access table type */     6,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR6FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR6_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR7 */
        /* access table type */     2,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR7FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR7_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8328)
    {   /* table name               INT_ESW_RTL8328_TSSCR8 */
        /* access table type */     10,
        /* table size */            29,
        /* total data registers */  1,
        /* total field numbers */   ESW_TSSCR8FIELD_LIST_END,
        /* table fields */          RTL8328_TSSCR8_FIELDS
    },
#endif
};

