/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 32577 $
 * $Date: 2012-09-10 20:04:41 +0800 (Mon, 10 Sep 2012) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/cypress/rtk_cypress_table_struct.h>

#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_IP_MC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_CAM_IP_MC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_ZEROtf */
        /* lsp */   64,
        /* len */   20,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_IP_MC_SIP_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_SIPtf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_FID_RVIDtf */
        /* lsp */   18,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_CAM_IP_MC_SIP_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_MC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_CAM_MC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_CAM_MC_MACtf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     CYPRESS_L2_CAM_MC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_MC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_MC_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_UC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_CAM_UC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_CAM_UC_MACtf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     CYPRESS_L2_CAM_UC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_SLPtf */
        /* lsp */   24,
        /* len */   6,
    },
    {   /* name     CYPRESS_L2_CAM_UC_AGEtf */
        /* lsp */   21,
        /* len */   3,
    },
    {   /* name     CYPRESS_L2_CAM_UC_SA_BLKtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_DA_BLKtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_STATICtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_SUSPENDtf */
        /* lsp */   17,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_NEXT_HOPtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_CAM_UC_VIDtf */
        /* lsp */   4,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_IP_MC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_IP_MC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_IP_MC_ZEROtf */
        /* lsp */   64,
        /* len */   20,
    },
    {   /* name     CYPRESS_L2_IP_MC_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_IP_MC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_IP_MC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_IP_MC_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_IP_MC_SIP_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_IP_MC_SIP_SIPtf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_IP_MC_SIP_GIPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     CYPRESS_L2_IP_MC_SIP_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_IP_MC_SIP_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_IP_MC_SIP_FID_RVIDtf */
        /* lsp */   18,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_IP_MC_SIP_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_MC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_MC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_MC_MACtf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     CYPRESS_L2_MC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_MC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_MC_MC_PMSK_IDXtf */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_NEXT_HOP_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_NEXT_HOP_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_MACtf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_RSVDtf */
        /* lsp */   32,
        /* len */   4,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_SLPtf */
        /* lsp */   24,
        /* len */   6,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_AGEtf */
        /* lsp */   21,
        /* len */   3,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_SA_BLKtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_DA_BLKtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_STATICtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_SUSPENDtf */
        /* lsp */   17,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_NEXT_HOPtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_VLAN_TARGETtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NEXT_HOP_ROUTE_IDXtf */
        /* lsp */   4,
        /* len */   11,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_NH_LEGACY_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_NH_LEGACY_HOSTMAC_IDXtf */
        /* lsp */   45,
        /* len */   11,
    },
    {   /* name     CYPRESS_L2_NH_LEGACY_VID_SELtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_NH_LEGACY_DVIDtf */
        /* lsp */   32,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_NH_LEGACY_DPAtf */
        /* lsp */   24,
        /* len */   6,
    },
    {   /* name     CYPRESS_L2_NH_LEGACY_NEXT_HOPtf */
        /* lsp */   16,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_UC_FIELDS[] = 
{
    {   /* name     CYPRESS_L2_UC_FID_RVIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     CYPRESS_L2_UC_MACtf */
        /* lsp */   36,
        /* len */   48,
    },
    {   /* name     CYPRESS_L2_UC_RSVDtf */
        /* lsp */   32,
        /* len */   4,
    },
    {   /* name     CYPRESS_L2_UC_IP_MCtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_IP6_MCtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_SLPtf */
        /* lsp */   24,
        /* len */   6,
    },
    {   /* name     CYPRESS_L2_UC_AGEtf */
        /* lsp */   21,
        /* len */   3,
    },
    {   /* name     CYPRESS_L2_UC_SA_BLKtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_DA_BLKtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_STATICtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_SUSPENDtf */
        /* lsp */   17,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_NEXT_HOPtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     CYPRESS_L2_UC_VIDtf */
        /* lsp */   4,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MC_PMSK_FIELDS[] = 
{
    {   /* name     CYPRESS_MC_PMSK_PMSKtf */
        /* lsp */   11,
        /* len */   53,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_UNTAG_FIELDS[] = 
{
    {   /* name     CYPRESS_UNTAG_PMSKtf */
        /* lsp */   11,
        /* len */   53,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_FIELDS[] = 
{
    {   /* name     CYPRESS_VLAN_MBRtf */
        /* lsp */   43,
        /* len */   53,
    },
    {   /* name     CYPRESS_VLAN_FID_MSTItf */
        /* lsp */   35,
        /* len */   8,
    },
    {   /* name     CYPRESS_VLAN_L2_HASH_KEY_UCtf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_L2_HASH_KEY_MCtf */
        /* lsp */   33,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_VLAN_PROFILEtf */
        /* lsp */   30,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_EGR_CNVT_FIELDS[] = 
{
    {   /* name     CYPRESS_VLAN_EGR_CNVT_VALIDtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_ORG_VIDtf */
        /* lsp */   115,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_ORG_VID_RNG_CHKtf */
        /* lsp */   83,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_ORG_PRItf */
        /* lsp */   80,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_PORT_IDtf */
        /* lsp */   74,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_BMSK_VALIDtf */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_BMSK_ORG_VIDtf */
        /* lsp */   61,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_BMSK_ORG_VID_RNG_CHKtf */
        /* lsp */   29,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_BMSK_ORG_PRItf */
        /* lsp */   26,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_BMSK_PORT_IDtf */
        /* lsp */   20,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_VID_SHIFTtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_NEW_VIDtf */
        /* lsp */   7,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_PRI_ASSIGNtf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_NEW_PRItf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_TPID_ASSIGNtf */
        /* lsp */   2,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_EGR_CNVT_TPID_IDXtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_IGR_CNVT_FIELDS[] = 
{
    {   /* name     CYPRESS_VLAN_IGR_CNVT_VALIDtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_IVIDtf */
        /* lsp */   147,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_IVID_RNG_CHKtf */
        /* lsp */   115,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_IPRItf */
        /* lsp */   112,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_PORTIDtf */
        /* lsp */   105,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_VALIDtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_IVIDtf */
        /* lsp */   92,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_IVID_RNG_CHKtf */
        /* lsp */   60,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_IPRItf */
        /* lsp */   57,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_RESERVEDtf */
        /* lsp */   56,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_BMSK_PORTIDtf */
        /* lsp */   50,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_VID_SELtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_VID_SHIFTtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_NEW_VIDtf */
        /* lsp */   36,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_PRI_ASSIGNtf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_NEW_PRItf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_ITAG_STStf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_OTAG_STStf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_TPID_ASSIGNtf */
        /* lsp */   27,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IGR_CNVT_TPID_IDXtf */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_IP_SUBNET_BASED_FIELDS[] = 
{
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_VALIDtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_SIPtf */
        /* lsp */   127,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_PORTIDtf */
        /* lsp */   105,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_BMSK_VALIDtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_BMSK_SIPtf */
        /* lsp */   72,
        /* len */   32,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_BMSK_PORTIDtf */
        /* lsp */   50,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_VID_SELtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_VID_SHIFTtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_NEW_VIDtf */
        /* lsp */   36,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_PRI_ASSIGNtf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_NEW_PRItf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_ITAG_STStf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_OTAG_STStf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_TPID_ASSIGNtf */
        /* lsp */   27,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_IP_SUBNET_BASED_TPID_IDXtf */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_MAC_BASED_FIELDS[] = 
{
    {   /* name     CYPRESS_VLAN_MAC_BASED_VALIDtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_SMACtf */
        /* lsp */   111,
        /* len */   48,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_PORTIDtf */
        /* lsp */   105,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_BMSK_VALIDtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_BMSK_SMACtf */
        /* lsp */   56,
        /* len */   48,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_BMSK_PORTIDtf */
        /* lsp */   50,
        /* len */   6,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_VID_SELtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_VID_SHIFTtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_NEW_VIDtf */
        /* lsp */   36,
        /* len */   12,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_PRI_ASSIGNtf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_NEW_PRItf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_ITAG_STStf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_OTAG_STStf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_TPID_ASSIGNtf */
        /* lsp */   27,
        /* len */   1,
    },
    {   /* name     CYPRESS_VLAN_MAC_BASED_TPID_IDXtf */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MSTI_FIELDS[] = 
{
    {   /* name     CYPRESS_MSTI_STATE_PORT51tf */
        /* lsp */   126,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT50tf */
        /* lsp */   124,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT49tf */
        /* lsp */   122,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT48tf */
        /* lsp */   120,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT47tf */
        /* lsp */   118,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT46tf */
        /* lsp */   116,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT45tf */
        /* lsp */   114,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT44tf */
        /* lsp */   112,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT43tf */
        /* lsp */   110,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT42tf */
        /* lsp */   108,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT41tf */
        /* lsp */   106,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT40tf */
        /* lsp */   104,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT39tf */
        /* lsp */   102,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT38tf */
        /* lsp */   100,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT37tf */
        /* lsp */   98,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT36tf */
        /* lsp */   96,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT35tf */
        /* lsp */   94,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT34tf */
        /* lsp */   92,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT33tf */
        /* lsp */   90,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT32tf */
        /* lsp */   88,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT31tf */
        /* lsp */   86,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT30tf */
        /* lsp */   84,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT29tf */
        /* lsp */   82,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT28tf */
        /* lsp */   80,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT27tf */
        /* lsp */   78,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT26tf */
        /* lsp */   76,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT25tf */
        /* lsp */   74,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT24tf */
        /* lsp */   72,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT23tf */
        /* lsp */   70,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT22tf */
        /* lsp */   68,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT21tf */
        /* lsp */   66,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT20tf */
        /* lsp */   64,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT19tf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT18tf */
        /* lsp */   60,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT17tf */
        /* lsp */   58,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT16tf */
        /* lsp */   56,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT15tf */
        /* lsp */   54,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT14tf */
        /* lsp */   52,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT13tf */
        /* lsp */   50,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT12tf */
        /* lsp */   48,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT11tf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT10tf */
        /* lsp */   44,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT9tf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT8tf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT7tf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT6tf */
        /* lsp */   36,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT5tf */
        /* lsp */   34,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT4tf */
        /* lsp */   32,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT3tf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT2tf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT1tf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     CYPRESS_MSTI_STATE_PORT0tf */
        /* lsp */   24,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_METER_FIELDS[] = 
{
    {   /* name     CYPRESS_METER_TYPEtf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     CYPRESS_METER_COLOR_AWAREtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     CYPRESS_METER_LB0_RATEtf */
        /* lsp */   41,
        /* len */   20,
    },
    {   /* name     CYPRESS_METER_LB1_RATEtf */
        /* lsp */   21,
        /* len */   20,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_LOG_FIELDS[] = 
{
    {   /* name     CYPRESS_LOG_CNTRtf */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_OUT_Q_FIELDS[] = 
{
    {   /* name     CYPRESS_OUT_Q_Q0_USED_PAGE_CNTtf */
        /* lsp */   244,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q0_MAX_USED_PAGE_CNTtf */
        /* lsp */   232,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q1_USED_PAGE_CNTtf */
        /* lsp */   220,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q1_MAX_USED_PAGE_CNTtf */
        /* lsp */   208,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q2_USED_PAGE_CNTtf */
        /* lsp */   196,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q2_MAX_USED_PAGE_CNTtf */
        /* lsp */   184,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q3_USED_PAGE_CNTtf */
        /* lsp */   172,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q3_MAX_USED_PAGE_CNTtf */
        /* lsp */   160,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q4_USED_PAGE_CNTtf */
        /* lsp */   148,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q4_MAX_USED_PAGE_CNTtf */
        /* lsp */   136,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q5_USED_PAGE_CNTtf */
        /* lsp */   124,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q5_MAX_USED_PAGE_CNTtf */
        /* lsp */   112,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q6_USED_PAGE_CNTtf */
        /* lsp */   100,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q6_MAX_USED_PAGE_CNTtf */
        /* lsp */   88,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q7_USED_PAGE_CNTtf */
        /* lsp */   76,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_Q7_MAX_USED_PAGE_CNTtf */
        /* lsp */   64,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_PE_USED_PAGE_CNTtf */
        /* lsp */   52,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_PE_MAX_USED_PAGE_CNTtf */
        /* lsp */   40,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_P_EGR_DROP_ON_THRtf */
        /* lsp */   28,
        /* len */   12,
    },
    {   /* name     CYPRESS_OUT_Q_P_EGR_DROP_OFF_THRtf */
        /* lsp */   16,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_SCHED_FIELDS[] = 
{
    {   /* name     CYPRESS_SCHED_LB_APR_Q7tf */
        /* lsp */   268,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q6tf */
        /* lsp */   248,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q5tf */
        /* lsp */   228,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q4tf */
        /* lsp */   208,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q3tf */
        /* lsp */   188,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q2tf */
        /* lsp */   168,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q1tf */
        /* lsp */   148,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_LB_APR_Q0tf */
        /* lsp */   128,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q7tf */
        /* lsp */   118,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q6tf */
        /* lsp */   108,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q5tf */
        /* lsp */   98,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q4tf */
        /* lsp */   88,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q3tf */
        /* lsp */   78,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q2tf */
        /* lsp */   68,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q1tf */
        /* lsp */   58,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_WEIGHT_Q0tf */
        /* lsp */   48,
        /* len */   10,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q7tf */
        /* lsp */   47,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q6tf */
        /* lsp */   46,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q5tf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q4tf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q3tf */
        /* lsp */   43,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q2tf */
        /* lsp */   42,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q1tf */
        /* lsp */   41,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_FIX_TKN_Q0tf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     CYPRESS_SCHED_EGR_RATEtf */
        /* lsp */   20,
        /* len */   20,
    },
    {   /* name     CYPRESS_SCHED_SCHED_TYPEtf */
        /* lsp */   19,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_EACL_FIELDS[] = 
{
    {   /* name     CYPRESS_EACL_FIELD_11tf */
        /* lsp */   528,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_10tf */
        /* lsp */   512,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_9tf */
        /* lsp */   496,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_8tf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_7tf */
        /* lsp */   464,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_6tf */
        /* lsp */   448,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_5tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_4tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_3tf */
        /* lsp */   400,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_2tf */
        /* lsp */   384,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_1tf */
        /* lsp */   368,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_FIELD_0tf */
        /* lsp */   352,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_SPMMASK_FIXtf */
        /* lsp */   350,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_SPNtf */
        /* lsp */   344,
        /* len */   6,
    },
    {   /* name     CYPRESS_EACL_MGNT_VLANtf */
        /* lsp */   343,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_SWITCHMACtf */
        /* lsp */   342,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_NOT_FIRST_FRAGtf */
        /* lsp */   341,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_FRAME_TYPE_L4tf */
        /* lsp */   338,
        /* len */   3,
    },
    {   /* name     CYPRESS_EACL_FRAME_TYPEtf */
        /* lsp */   336,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_OTAG_FMTtf */
        /* lsp */   335,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ITAG_FMTtf */
        /* lsp */   334,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_OTAG_EXISTtf */
        /* lsp */   333,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ITAG_EXISTtf */
        /* lsp */   332,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_FRAME_TYPE_L2tf */
        /* lsp */   330,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_TIDtf */
        /* lsp */   328,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_11tf */
        /* lsp */   312,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_10tf */
        /* lsp */   296,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_9tf */
        /* lsp */   280,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_8tf */
        /* lsp */   264,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_7tf */
        /* lsp */   248,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_6tf */
        /* lsp */   232,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_5tf */
        /* lsp */   216,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_4tf */
        /* lsp */   200,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_3tf */
        /* lsp */   184,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_2tf */
        /* lsp */   168,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_1tf */
        /* lsp */   152,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_FIELD_0tf */
        /* lsp */   136,
        /* len */   16,
    },
    {   /* name     CYPRESS_EACL_BMSK_SPMMASK_FIXtf */
        /* lsp */   134,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_BMSK_SPNtf */
        /* lsp */   128,
        /* len */   6,
    },
    {   /* name     CYPRESS_EACL_BMSK_MGNT_VLANtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_SWITCHMACtf */
        /* lsp */   126,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_NOT_FIRST_FRAGtf */
        /* lsp */   125,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_FRAME_TYPE_L4tf */
        /* lsp */   122,
        /* len */   3,
    },
    {   /* name     CYPRESS_EACL_BMSK_FRAME_TYPEtf */
        /* lsp */   120,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_BMSK_OTAG_FMTtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_ITAG_FMTtf */
        /* lsp */   118,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_OTAG_EXISTtf */
        /* lsp */   117,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_ITAG_EXISTtf */
        /* lsp */   116,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_BMSK_FRAME_TYPE_L2tf */
        /* lsp */   114,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_BMSK_TIDtf */
        /* lsp */   112,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_VALIDtf */
        /* lsp */   111,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_NOTtf */
        /* lsp */   110,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_AND1tf */
        /* lsp */   109,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_AND2tf */
        /* lsp */   108,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_TAG_STStf */
        /* lsp */   107,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_QOS_REMARKtf */
        /* lsp */   106,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_PRItf */
        /* lsp */   105,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_OVIDtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_IVIDtf */
        /* lsp */   103,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_METERtf */
        /* lsp */   102,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_MIRRORtf */
        /* lsp */   101,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_LOGtf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_ACT_MSK_FWDtf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_FWD_ACTtf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     CYPRESS_EACL_FWD_PORT_INFOtf */
        /* lsp */   82,
        /* len */   12,
    },
    {   /* name     CYPRESS_EACL_LOG_ACTtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_LOG_IDXtf */
        /* lsp */   70,
        /* len */   11,
    },
    {   /* name     CYPRESS_EACL_MIR_ACTtf */
        /* lsp */   69,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_MIR_IDXtf */
        /* lsp */   67,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_METER_IDXtf */
        /* lsp */   58,
        /* len */   9,
    },
    {   /* name     CYPRESS_EACL_IVLAN_TPID_ACTtf */
        /* lsp */   57,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_IVLAN_VID_ACTtf */
        /* lsp */   55,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_IVLAN_TPID_IDXtf */
        /* lsp */   53,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_IVLAN_VIDtf */
        /* lsp */   41,
        /* len */   12,
    },
    {   /* name     CYPRESS_EACL_OVLAN_TPID_ACTtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_OVLAN_VID_ACTtf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_OVLAN_TPID_IDXtf */
        /* lsp */   36,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_OVLAN_VIDtf */
        /* lsp */   24,
        /* len */   12,
    },
    {   /* name     CYPRESS_EACL_PRI_ACTtf */
        /* lsp */   23,
        /* len */   1,
    },
    {   /* name     CYPRESS_EACL_INT_PRItf */
        /* lsp */   20,
        /* len */   3,
    },
    {   /* name     CYPRESS_EACL_RMK_ACTtf */
        /* lsp */   16,
        /* len */   3,
    },
    {   /* name     CYPRESS_EACL_RMK_VALtf */
        /* lsp */   10,
        /* len */   6,
    },
    {   /* name     CYPRESS_EACL_TAG_STS_OUTERtf */
        /* lsp */   8,
        /* len */   2,
    },
    {   /* name     CYPRESS_EACL_TAG_STS_INNERtf */
        /* lsp */   6,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_IACL_FIELDS[] = 
{
    {   /* name     CYPRESS_IACL_FIELD_11tf */
        /* lsp */   528,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_10tf */
        /* lsp */   512,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_9tf */
        /* lsp */   496,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_8tf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_7tf */
        /* lsp */   464,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_6tf */
        /* lsp */   448,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_5tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_4tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_3tf */
        /* lsp */   400,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_2tf */
        /* lsp */   384,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_1tf */
        /* lsp */   368,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_FIELD_0tf */
        /* lsp */   352,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_SPMMASK_FIXtf */
        /* lsp */   350,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_SPNtf */
        /* lsp */   344,
        /* len */   6,
    },
    {   /* name     CYPRESS_IACL_MGNT_VLANtf */
        /* lsp */   343,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_SWITCHMACtf */
        /* lsp */   342,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_NOT_FIRST_FRAGtf */
        /* lsp */   341,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_FRAME_TYPE_L4tf */
        /* lsp */   338,
        /* len */   3,
    },
    {   /* name     CYPRESS_IACL_FRAME_TYPEtf */
        /* lsp */   336,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_OTAG_FMTtf */
        /* lsp */   335,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ITAG_FMTtf */
        /* lsp */   334,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_OTAG_EXISTtf */
        /* lsp */   333,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ITAG_EXISTtf */
        /* lsp */   332,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_FRAME_TYPE_L2tf */
        /* lsp */   330,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_TIDtf */
        /* lsp */   328,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_11tf */
        /* lsp */   312,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_10tf */
        /* lsp */   296,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_9tf */
        /* lsp */   280,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_8tf */
        /* lsp */   264,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_7tf */
        /* lsp */   248,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_6tf */
        /* lsp */   232,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_5tf */
        /* lsp */   216,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_4tf */
        /* lsp */   200,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_3tf */
        /* lsp */   184,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_2tf */
        /* lsp */   168,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_1tf */
        /* lsp */   152,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_FIELD_0tf */
        /* lsp */   136,
        /* len */   16,
    },
    {   /* name     CYPRESS_IACL_BMSK_SPMMASK_FIXtf */
        /* lsp */   134,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_BMSK_SPNtf */
        /* lsp */   128,
        /* len */   6,
    },
    {   /* name     CYPRESS_IACL_BMSK_MGNT_VLANtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_SWITCHMACtf */
        /* lsp */   126,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_NOT_FIRST_FRAGtf */
        /* lsp */   125,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_FRAME_TYPE_L4tf */
        /* lsp */   122,
        /* len */   3,
    },
    {   /* name     CYPRESS_IACL_BMSK_FRAME_TYPEtf */
        /* lsp */   120,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_BMSK_OTAG_FMTtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_ITAG_FMTtf */
        /* lsp */   118,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_OTAG_EXISTtf */
        /* lsp */   117,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_ITAG_EXISTtf */
        /* lsp */   116,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BMSK_FRAME_TYPE_L2tf */
        /* lsp */   114,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_BMSK_TIDtf */
        /* lsp */   112,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_VALIDtf */
        /* lsp */   111,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_NOTtf */
        /* lsp */   110,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_AND1tf */
        /* lsp */   109,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_AND2tf */
        /* lsp */   108,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_BYPASStf */
        /* lsp */   107,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_MPLStf */
        /* lsp */   106,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_PRItf */
        /* lsp */   105,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_OVIDtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_IVIDtf */
        /* lsp */   103,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_METERtf */
        /* lsp */   102,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_MIRRORtf */
        /* lsp */   101,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_LOGtf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_ACT_MSK_FWDtf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_FWD_ACTtf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     CYPRESS_IACL_FWD_PORT_INFOtf */
        /* lsp */   82,
        /* len */   14,
    },
    {   /* name     CYPRESS_IACL_LOG_ACTtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_LOG_IDXtf */
        /* lsp */   70,
        /* len */   11,
    },
    {   /* name     CYPRESS_IACL_MIR_IDXtf */
        /* lsp */   67,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_METER_IDXtf */
        /* lsp */   58,
        /* len */   9,
    },
    {   /* name     CYPRESS_IACL_IVLAN_ACTtf */
        /* lsp */   55,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_IVLAN_DATAtf */
        /* lsp */   41,
        /* len */   12,
    },
    {   /* name     CYPRESS_IACL_OVLAN_ACTtf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     CYPRESS_IACL_OVLAN_DATAtf */
        /* lsp */   24,
        /* len */   12,
    },
    {   /* name     CYPRESS_IACL_INT_PRItf */
        /* lsp */   20,
        /* len */   3,
    },
    {   /* name     CYPRESS_IACL_MPLS_ACTtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_MPLS_LIB_IDXtf */
        /* lsp */   10,
        /* len */   9,
    },
    {   /* name     CYPRESS_IACL_BYPASS_ALLtf */
        /* lsp */   9,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BYPASS_IGR_STPtf */
        /* lsp */   8,
        /* len */   1,
    },
    {   /* name     CYPRESS_IACL_BYPASS_IBC_SCtf */
        /* lsp */   7,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_SPG_PORT_FIELDS[] = 
{
    {   /* name     CYPRESS_SPG_PORT_PKT_CNTtf */
        /* lsp */   192,
        /* len */   32,
    },
    {   /* name     CYPRESS_SPG_PORT_BAD_CRC_EN_0tf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_TYPE_0tf */
        /* lsp */   189,
        /* len */   2,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_RNDM_OFFSET_0tf */
        /* lsp */   184,
        /* len */   5,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_RNDM_EN_0tf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_SA_INC_0tf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_DA_INC_0tf */
        /* lsp */   181,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_PKT_CNT_0tf */
        /* lsp */   165,
        /* len */   16,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_RNG_START_0tf */
        /* lsp */   151,
        /* len */   14,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_RNG_END_0tf */
        /* lsp */   137,
        /* len */   14,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_DA_REPEAT_CNT_0tf */
        /* lsp */   122,
        /* len */   15,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_SA_REPEAT_CNT_0tf */
        /* lsp */   107,
        /* len */   15,
    },
    {   /* name     CYPRESS_SPG_PORT_BAD_CRC_EN_1tf */
        /* lsp */   106,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_TYPE_1tf */
        /* lsp */   104,
        /* len */   2,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_RNDM_OFFSET_1tf */
        /* lsp */   99,
        /* len */   5,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_RNDM_EN_1tf */
        /* lsp */   98,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_SA_INC_1tf */
        /* lsp */   97,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_DA_INC_1tf */
        /* lsp */   96,
        /* len */   1,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_PKT_CNT_1tf */
        /* lsp */   80,
        /* len */   16,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_RNG_START_1tf */
        /* lsp */   66,
        /* len */   14,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_LEN_RNG_END_1tf */
        /* lsp */   52,
        /* len */   14,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_DA_REPEAT_CNT_1tf */
        /* lsp */   37,
        /* len */   15,
    },
    {   /* name     CYPRESS_SPG_PORT_STREAM_SA_REPEAT_CNT_1tf */
        /* lsp */   22,
        /* len */   15,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_ROUTING_FIELDS[] = 
{
    {   /* name     CYPRESS_ROUTING_GATEWAY_MACtf */
        /* lsp */   16,
        /* len */   48,
    },
    {   /* name     CYPRESS_ROUTING_SW_MAC_IDXtf */
        /* lsp */   12,
        /* len */   4,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MPLS_LIB_FIELDS[] = 
{
    {   /* name     CYPRESS_MPLS_LIB_I_LABELtf */
        /* lsp */   44,
        /* len */   20,
    },
    {   /* name     CYPRESS_MPLS_LIB_I_EXPtf */
        /* lsp */   41,
        /* len */   3,
    },
    {   /* name     CYPRESS_MPLS_LIB_I_TTLtf */
        /* lsp */   33,
        /* len */   8,
    },
    {   /* name     CYPRESS_MPLS_LIB_O_LABELtf */
        /* lsp */   13,
        /* len */   20,
    },
    {   /* name     CYPRESS_MPLS_LIB_O_EXPtf */
        /* lsp */   10,
        /* len */   3,
    },
    {   /* name     CYPRESS_MPLS_LIB_O_TTLtf */
        /* lsp */   2,
        /* len */   8,
    },
};
#endif

