/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision: 50053 $
 * $Date: 2014-08-11 17:47:46 +0800 (Mon, 11 Aug 2014) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/cypress/rtk_cypress_table_struct.h>
#include <hal/chipdef/cypress/rtk_cypress_tableField_list.h>

rtk_table_t rtk_cypress_table_list[] =
{
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_CAM_IP_MC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_CAM_IP_MCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_CAM_IP_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_CAM_IP_MC_SIP */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_CAM_IP_MC_SIPFIELD_LIST_END,
        /* table fields */          RTL8390_L2_CAM_IP_MC_SIP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_CAM_MC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_CAM_MCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_CAM_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_CAM_UC */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_CAM_UCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_CAM_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_IP_MC */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_IP_MCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_IP_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_IP_MC_SIP */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_IP_MC_SIPFIELD_LIST_END,
        /* table fields */          RTL8390_L2_IP_MC_SIP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_MC */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_MCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_NEXT_HOP */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_NEXT_HOPFIELD_LIST_END,
        /* table fields */          RTL8390_L2_NEXT_HOP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_NH_LEGACY */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_NH_LEGACYFIELD_LIST_END,
        /* table fields */          RTL8390_L2_NH_LEGACY_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_L2_UC */
        /* access table type */     0,
        /* table size */            16384,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_L2_UCFIELD_LIST_END,
        /* table fields */          RTL8390_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_MC_PMSK */
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_MC_PMSKFIELD_LIST_END,
        /* table fields */          RTL8390_MC_PMSK_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_UNTAG */
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_UNTAGFIELD_LIST_END,
        /* table fields */          RTL8390_UNTAG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_VLAN */
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  3,
        /* total field numbers */   CYPRESS_VLANFIELD_LIST_END,
        /* table fields */          RTL8390_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_VLAN_EGR_CNVT */
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  4,
        /* total field numbers */   CYPRESS_VLAN_EGR_CNVTFIELD_LIST_END,
        /* table fields */          RTL8390_VLAN_EGR_CNVT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_VLAN_IGR_CNVT */
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  5,
        /* total field numbers */   CYPRESS_VLAN_IGR_CNVTFIELD_LIST_END,
        /* table fields */          RTL8390_VLAN_IGR_CNVT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_VLAN_IP_SUBNET_BASED */
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  5,
        /* total field numbers */   CYPRESS_VLAN_IP_SUBNET_BASEDFIELD_LIST_END,
        /* table fields */          RTL8390_VLAN_IP_SUBNET_BASED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_VLAN_MAC_BASED */
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  5,
        /* total field numbers */   CYPRESS_VLAN_MAC_BASEDFIELD_LIST_END,
        /* table fields */          RTL8390_VLAN_MAC_BASED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_MSTI */
        /* access table type */     5,
        /* table size */            256,
        /* total data registers */  4,
        /* total field numbers */   CYPRESS_MSTIFIELD_LIST_END,
        /* table fields */          RTL8390_MSTI_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_METER */
        /* access table type */     3,
        /* table size */            512,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_METERFIELD_LIST_END,
        /* table fields */          RTL8390_METER_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_LOG */
        /* access table type */     4,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_LOGFIELD_LIST_END,
        /* table fields */          RTL8390_LOG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_OUT_Q */
        /* access table type */     2,
        /* table size */            53,
        /* total data registers */  8,
        /* total field numbers */   CYPRESS_OUT_QFIELD_LIST_END,
        /* table fields */          RTL8390_OUT_Q_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_SCHED */
        /* access table type */     0,
        /* table size */            53,
        /* total data registers */  9,
        /* total field numbers */   CYPRESS_SCHEDFIELD_LIST_END,
        /* table fields */          RTL8390_SCHED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_EACL */
        /* access table type */     2,
        /* table size */            2304,
        /* total data registers */  17,
        /* total field numbers */   CYPRESS_EACLFIELD_LIST_END,
        /* table fields */          RTL8390_EACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_IACL */
        /* access table type */     2,
        /* table size */            2304,
        /* total data registers */  17,
        /* total field numbers */   CYPRESS_IACLFIELD_LIST_END,
        /* table fields */          RTL8390_IACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_SPG_PORT */
        /* access table type */     1,
        /* table size */            52,
        /* total data registers */  7,
        /* total field numbers */   CYPRESS_SPG_PORTFIELD_LIST_END,
        /* table fields */          RTL8390_SPG_PORT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_ROUTING */
        /* access table type */     2,
        /* table size */            2048,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_ROUTINGFIELD_LIST_END,
        /* table fields */          RTL8390_ROUTING_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL8390)
    {   /* table name               INT_CYPRESS_RTL8390_MPLS_LIB */
        /* access table type */     3,
        /* table size */            256,
        /* total data registers */  2,
        /* total field numbers */   CYPRESS_MPLS_LIBFIELD_LIST_END,
        /* table fields */          RTL8390_MPLS_LIB_FIELDS
    },
#endif
};

#if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
rtk_tableName_t rtk_cypress_tableName_list[] =
{
    {"L2_CAM_IP_MC"},
    {"L2_CAM_IP_MC_SIP"},
    {"L2_CAM_MC"},
    {"L2_CAM_UC"},
    {"L2_IP_MC"},
    {"L2_IP_MC_SIP"},
    {"L2_MC"},
    {"L2_NEXT_HOP"},
    {"L2_NH_LEGACY"},
    {"L2_UC"},
    {"MC_PMSK"},
    {"UNTAG"},
    {"VLAN"},
    {"VLAN_EGR_CNVT"},
    {"VLAN_IGR_CNVT"},
    {"VLAN_IP_SUBNET_BASED"},
    {"VLAN_MAC_BASED"},
    {"MSTI"},
    {"METER"},
    {"LOG"},
    {"OUT_Q"},
    {"SCHED"},
    {"EACL"},
    {"IACL"},
    {"SPG_PORT"},
    {"ROUTING"},
    {"MPLS_LIB"},
};
#endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */

